/*
###############################################################
#  Generated by:      Cadence Innovus 19.12-s087_1
#  OS:                Linux x86_64(Host ID pdk5)
#  Generated on:      Tue Apr 28 20:11:43 2026
#  Design:            global_ctrl
#  Command:           saveNetlist ./output/global_ctrl/global_ctrl_enc.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : S-2021.06-SP1
// Date      : Tue Apr 28 19:24:57 2026
/////////////////////////////////////////////////////////////
module global_ctrl (
	clk, 
	rstn, 
	p_en, 
	en_g, 
	wr_data_in_g, 
	rd_vld_bus, 
	rd_data_out_bus, 
	p_out_vld_bus, 
	p_out_bus, 
	couple_en, 
	wr_data_in_g_d2, 
	rd_vld_g, 
	rd_data_out_g, 
	wr_vld_bus, 
	rd_rdy_bus, 
	p_code_vld_bus, 
	p_out_vld_g, 
	p_out_g);
   input clk;
   input rstn;
   input p_en;
   input en_g;
   input wr_data_in_g;
   input [7:0] rd_vld_bus;
   input [7:0] rd_data_out_bus;
   input [7:0] p_out_vld_bus;
   input [7:0] p_out_bus;
   output couple_en;
   output wr_data_in_g_d2;
   output rd_vld_g;
   output rd_data_out_g;
   output [7:0] wr_vld_bus;
   output [7:0] rd_rdy_bus;
   output [7:0] p_code_vld_bus;
   output p_out_vld_g;
   output p_out_g;

   // Internal wires
   wire FE_PHN69_phase_row_id_1;
   wire FE_PHN68_n186;
   wire FE_PHN67_n120;
   wire FE_PHN66_n85;
   wire FE_PHN65_n70;
   wire FE_PHN64_n76;
   wire FE_PHN63_n72;
   wire FE_PHN62_n1210;
   wire FE_PHN61_n69;
   wire FE_PHN60_n1190;
   wire FE_PHN59_n84;
   wire FE_PHN58_n118;
   wire FE_PHN57_n71;
   wire FE_PHN56_n73;
   wire FE_PHN55_dl_next_state;
   wire FE_PHN54_n90;
   wire FE_PHN53_n870;
   wire FE_PHN52_phase_row_id_1;
   wire FE_PHN51_phase_col_id_0;
   wire FE_PHN50_dl_cur_state;
   wire FE_PHN49_p_en_d1;
   wire FE_PHN48_row_id_2;
   wire FE_PHN47_col_id_6;
   wire FE_PHN46_ul_cur_state_0;
   wire FE_PHN45_phase_row_id_0;
   wire FE_PHN44_n194;
   wire FE_PHN43_phase_row_id_2;
   wire FE_PHN42_col_id_0;
   wire FE_PHN41_rd_row_id_0;
   wire FE_PHN40_row_id_0;
   wire FE_PHN39_wr_data_in_g_d1;
   wire FE_PHN38_dl_cur_state_d1;
   wire FE_PHN37_phase_row_id_d1_1;
   wire FE_PHN36_rd_row_id_2;
   wire FE_PHN35_phase_row_id_d1_0;
   wire FE_PHN34_phase_row_id_d1_2;
   wire FE_PHN33_rd_row_id_1;
   wire FE_PHN32_ul_cur_state_1;
   wire CTS_1;
   wire FE_OFN31_n195;
   wire FE_OFN30_n1470;
   wire FE_OFN29_p_out_g;
   wire FE_OFN28_p_out_vld_g;
   wire FE_OFN27_rd_data_out_g;
   wire FE_OFN26_rd_vld_g;
   wire FE_OFN25_wr_data_in_g_d2;
   wire FE_OFN24_couple_en;
   wire FE_OFN23_p_code_vld_bus_0;
   wire FE_OFN22_p_code_vld_bus_1;
   wire FE_OFN21_p_code_vld_bus_2;
   wire FE_OFN20_p_code_vld_bus_3;
   wire FE_OFN19_p_code_vld_bus_4;
   wire FE_OFN18_p_code_vld_bus_5;
   wire FE_OFN17_p_code_vld_bus_6;
   wire FE_OFN16_p_code_vld_bus_7;
   wire FE_OFN15_rd_rdy_bus_0;
   wire FE_OFN14_rd_rdy_bus_1;
   wire FE_OFN13_rd_rdy_bus_2;
   wire FE_OFN12_rd_rdy_bus_3;
   wire FE_OFN11_rd_rdy_bus_4;
   wire FE_OFN10_rd_rdy_bus_5;
   wire FE_OFN9_rd_rdy_bus_6;
   wire FE_OFN8_rd_rdy_bus_7;
   wire FE_OFN7_wr_vld_bus_0;
   wire FE_OFN6_wr_vld_bus_1;
   wire FE_OFN5_wr_vld_bus_2;
   wire FE_OFN4_wr_vld_bus_3;
   wire FE_OFN3_wr_vld_bus_4;
   wire FE_OFN2_wr_vld_bus_5;
   wire FE_OFN1_wr_vld_bus_6;
   wire FE_OFN0_wr_vld_bus_7;
   wire en_g_d1;
   wire wr_data_in_g_d1;
   wire p_en_d1;
   wire p_en_d2;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n820;
   wire n830;
   wire n840;
   wire ul_cur_state_d1_0_;
   wire n870;
   wire n90;
   wire dl_cur_state;
   wire dl_next_state;
   wire n1170;
   wire n118;
   wire n1190;
   wire n120;
   wire n1210;
   wire n122;
   wire n1230;
   wire n124;
   wire n1250;
   wire n126;
   wire n1270;
   wire n128;
   wire n1290;
   wire dl_cur_state_d1;
   wire dl_cur_state_d2;
   wire n132;
   wire n134;
   wire n1350;
   wire n136;
   wire n1370;
   wire n138;
   wire n1390;
   wire n140;
   wire n1410;
   wire n142;
   wire n1430;
   wire n144;
   wire n1450;
   wire n146;
   wire n1470;
   wire n148;
   wire n1490;
   wire n1500;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire [1:0] ul_cur_state;
   wire [8:0] col_id;
   wire [2:0] row_id;
   wire [2:0] rd_row_id;
   wire [2:0] rd_row_id_d1;
   wire [4:0] phase_col_id;
   wire [2:0] phase_row_id;
   wire [2:0] phase_row_id_d1;
   wire [2:0] phase_row_id_d2;

   CKBD1BWP FE_PHC69_phase_row_id_1 (.I(phase_row_id[1]),
	.Z(FE_PHN69_phase_row_id_1));
   CKBD1BWP FE_PHC68_n186 (.I(n186),
	.Z(FE_PHN68_n186));
   DEL050D1BWP FE_PHC67_n120 (.I(n120),
	.Z(FE_PHN67_n120));
   DEL050D1BWP FE_PHC66_n85 (.I(n85),
	.Z(FE_PHN66_n85));
   DEL050D1BWP FE_PHC65_n70 (.I(n70),
	.Z(FE_PHN65_n70));
   DEL100D1BWP FE_PHC64_n76 (.I(n76),
	.Z(FE_PHN64_n76));
   DEL050D1BWP FE_PHC63_n72 (.I(n72),
	.Z(FE_PHN63_n72));
   DEL100D1BWP FE_PHC62_n1210 (.I(n1210),
	.Z(FE_PHN62_n1210));
   DEL050D1BWP FE_PHC61_n69 (.I(n69),
	.Z(FE_PHN61_n69));
   DEL050D1BWP FE_PHC60_n1190 (.I(n1190),
	.Z(FE_PHN60_n1190));
   DEL050D1BWP FE_PHC59_n84 (.I(n84),
	.Z(FE_PHN59_n84));
   DEL050D1BWP FE_PHC58_n118 (.I(n118),
	.Z(FE_PHN58_n118));
   DEL050D1BWP FE_PHC57_n71 (.I(n71),
	.Z(FE_PHN57_n71));
   DEL050D1BWP FE_PHC56_n73 (.I(n73),
	.Z(FE_PHN56_n73));
   DEL050D1BWP FE_PHC55_dl_next_state (.I(dl_next_state),
	.Z(FE_PHN55_dl_next_state));
   BUFFD1BWP FE_PHC54_n90 (.I(FE_PHN54_n90),
	.Z(n90));
   BUFFD1BWP FE_PHC53_n870 (.I(FE_PHN53_n870),
	.Z(n870));
   DEL100D1BWP FE_PHC52_phase_row_id_1 (.I(phase_row_id[1]),
	.Z(FE_PHN52_phase_row_id_1));
   DEL100D1BWP FE_PHC51_phase_col_id_0 (.I(phase_col_id[0]),
	.Z(FE_PHN51_phase_col_id_0));
   DEL100D1BWP FE_PHC50_dl_cur_state (.I(dl_cur_state),
	.Z(FE_PHN50_dl_cur_state));
   BUFFD1BWP FE_PHC49_p_en_d1 (.I(p_en_d1),
	.Z(FE_PHN49_p_en_d1));
   CKBD0BWP FE_PHC48_row_id_2 (.I(row_id[2]),
	.Z(FE_PHN48_row_id_2));
   DEL050D1BWP FE_PHC47_col_id_6 (.I(col_id[6]),
	.Z(FE_PHN47_col_id_6));
   CKBD0BWP FE_PHC46_ul_cur_state_0 (.I(ul_cur_state[0]),
	.Z(FE_PHN46_ul_cur_state_0));
   DEL175D1BWP FE_PHC45_phase_row_id_0 (.I(phase_row_id[0]),
	.Z(FE_PHN45_phase_row_id_0));
   DEL050D1BWP FE_PHC44_n194 (.I(n194),
	.Z(FE_PHN44_n194));
   DEL100D1BWP FE_PHC43_phase_row_id_2 (.I(phase_row_id[2]),
	.Z(FE_PHN43_phase_row_id_2));
   DEL100D1BWP FE_PHC42_col_id_0 (.I(col_id[0]),
	.Z(FE_PHN42_col_id_0));
   DEL125D1BWP FE_PHC41_rd_row_id_0 (.I(rd_row_id[0]),
	.Z(FE_PHN41_rd_row_id_0));
   BUFFD1BWP FE_PHC40_row_id_0 (.I(row_id[0]),
	.Z(FE_PHN40_row_id_0));
   DEL125D1BWP FE_PHC39_wr_data_in_g_d1 (.I(wr_data_in_g_d1),
	.Z(FE_PHN39_wr_data_in_g_d1));
   DEL125D1BWP FE_PHC38_dl_cur_state_d1 (.I(FE_PHN38_dl_cur_state_d1),
	.Z(dl_cur_state_d1));
   DEL125D1BWP FE_PHC37_phase_row_id_d1_1 (.I(phase_row_id_d1[1]),
	.Z(FE_PHN37_phase_row_id_d1_1));
   DEL125D1BWP FE_PHC36_rd_row_id_2 (.I(rd_row_id[2]),
	.Z(FE_PHN36_rd_row_id_2));
   DEL100D1BWP FE_PHC35_phase_row_id_d1_0 (.I(phase_row_id_d1[0]),
	.Z(FE_PHN35_phase_row_id_d1_0));
   DEL125D1BWP FE_PHC34_phase_row_id_d1_2 (.I(phase_row_id_d1[2]),
	.Z(FE_PHN34_phase_row_id_d1_2));
   DEL125D1BWP FE_PHC33_rd_row_id_1 (.I(rd_row_id[1]),
	.Z(FE_PHN33_rd_row_id_1));
   DEL050D1BWP FE_PHC32_ul_cur_state_1 (.I(ul_cur_state[1]),
	.Z(FE_PHN32_ul_cur_state_1));
   BUFFD20BWP CTS_ccl_a_buf_00003 (.I(clk),
	.Z(CTS_1));
   CKBD1BWP FE_OFC31_n195 (.I(n195),
	.Z(FE_OFN31_n195));
   CKBD1BWP FE_OFC30_n1470 (.I(n1470),
	.Z(FE_OFN30_n1470));
   CKBD8BWP FE_OFC29_p_out_g (.I(FE_OFN29_p_out_g),
	.Z(p_out_g));
   CKBD8BWP FE_OFC28_p_out_vld_g (.I(FE_OFN28_p_out_vld_g),
	.Z(p_out_vld_g));
   CKBD8BWP FE_OFC27_rd_data_out_g (.I(FE_OFN27_rd_data_out_g),
	.Z(rd_data_out_g));
   CKBD8BWP FE_OFC26_rd_vld_g (.I(FE_OFN26_rd_vld_g),
	.Z(rd_vld_g));
   CKBD8BWP FE_OFC25_wr_data_in_g_d2 (.I(FE_OFN25_wr_data_in_g_d2),
	.Z(wr_data_in_g_d2));
   CKBD8BWP FE_OFC24_couple_en (.I(FE_OFN24_couple_en),
	.Z(couple_en));
   CKBD8BWP FE_OFC23_p_code_vld_bus_0 (.I(FE_OFN23_p_code_vld_bus_0),
	.Z(p_code_vld_bus[0]));
   CKBD8BWP FE_OFC22_p_code_vld_bus_1 (.I(FE_OFN22_p_code_vld_bus_1),
	.Z(p_code_vld_bus[1]));
   CKBD8BWP FE_OFC21_p_code_vld_bus_2 (.I(FE_OFN21_p_code_vld_bus_2),
	.Z(p_code_vld_bus[2]));
   CKBD8BWP FE_OFC20_p_code_vld_bus_3 (.I(FE_OFN20_p_code_vld_bus_3),
	.Z(p_code_vld_bus[3]));
   CKBD8BWP FE_OFC19_p_code_vld_bus_4 (.I(FE_OFN19_p_code_vld_bus_4),
	.Z(p_code_vld_bus[4]));
   CKBD8BWP FE_OFC18_p_code_vld_bus_5 (.I(FE_OFN18_p_code_vld_bus_5),
	.Z(p_code_vld_bus[5]));
   CKBD8BWP FE_OFC17_p_code_vld_bus_6 (.I(FE_OFN17_p_code_vld_bus_6),
	.Z(p_code_vld_bus[6]));
   CKBD8BWP FE_OFC16_p_code_vld_bus_7 (.I(FE_OFN16_p_code_vld_bus_7),
	.Z(p_code_vld_bus[7]));
   CKBD8BWP FE_OFC15_rd_rdy_bus_0 (.I(FE_OFN15_rd_rdy_bus_0),
	.Z(rd_rdy_bus[0]));
   CKBD8BWP FE_OFC14_rd_rdy_bus_1 (.I(FE_OFN14_rd_rdy_bus_1),
	.Z(rd_rdy_bus[1]));
   CKBD8BWP FE_OFC13_rd_rdy_bus_2 (.I(FE_OFN13_rd_rdy_bus_2),
	.Z(rd_rdy_bus[2]));
   CKBD8BWP FE_OFC12_rd_rdy_bus_3 (.I(FE_OFN12_rd_rdy_bus_3),
	.Z(rd_rdy_bus[3]));
   CKBD8BWP FE_OFC11_rd_rdy_bus_4 (.I(FE_OFN11_rd_rdy_bus_4),
	.Z(rd_rdy_bus[4]));
   CKBD8BWP FE_OFC10_rd_rdy_bus_5 (.I(FE_OFN10_rd_rdy_bus_5),
	.Z(rd_rdy_bus[5]));
   CKBD8BWP FE_OFC9_rd_rdy_bus_6 (.I(FE_OFN9_rd_rdy_bus_6),
	.Z(rd_rdy_bus[6]));
   CKBD8BWP FE_OFC8_rd_rdy_bus_7 (.I(FE_OFN8_rd_rdy_bus_7),
	.Z(rd_rdy_bus[7]));
   CKBD8BWP FE_OFC7_wr_vld_bus_0 (.I(FE_OFN7_wr_vld_bus_0),
	.Z(wr_vld_bus[0]));
   CKBD8BWP FE_OFC6_wr_vld_bus_1 (.I(FE_OFN6_wr_vld_bus_1),
	.Z(wr_vld_bus[1]));
   CKBD8BWP FE_OFC5_wr_vld_bus_2 (.I(FE_OFN5_wr_vld_bus_2),
	.Z(wr_vld_bus[2]));
   CKBD8BWP FE_OFC4_wr_vld_bus_3 (.I(FE_OFN4_wr_vld_bus_3),
	.Z(wr_vld_bus[3]));
   CKBD8BWP FE_OFC3_wr_vld_bus_4 (.I(FE_OFN3_wr_vld_bus_4),
	.Z(wr_vld_bus[4]));
   CKBD8BWP FE_OFC2_wr_vld_bus_5 (.I(FE_OFN2_wr_vld_bus_5),
	.Z(wr_vld_bus[5]));
   CKBD8BWP FE_OFC1_wr_vld_bus_6 (.I(FE_OFN1_wr_vld_bus_6),
	.Z(wr_vld_bus[6]));
   CKBD8BWP FE_OFC0_wr_vld_bus_7 (.I(FE_OFN0_wr_vld_bus_7),
	.Z(wr_vld_bus[7]));
   DFCNQD1BWP en_g_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(en_g),
	.Q(en_g_d1));
   DFCNQD1BWP wr_data_in_g_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(wr_data_in_g),
	.Q(wr_data_in_g_d1));
   DFCNQD1BWP p_en_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(p_en),
	.Q(p_en_d1));
   DFCNQD1BWP p_en_d2_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN49_p_en_d1),
	.Q(p_en_d2));
   DFCNQD1BWP col_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n68),
	.Q(col_id[0]));
   DFCNQD1BWP ul_cur_state_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN59_n84),
	.Q(ul_cur_state[1]));
   DFCNQD1BWP ul_cur_state_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN66_n85),
	.Q(ul_cur_state[0]));
   DFCNQD1BWP col_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN61_n69),
	.Q(col_id[1]));
   DFCNQD1BWP col_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN65_n70),
	.Q(col_id[2]));
   DFCNQD1BWP col_id_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN57_n71),
	.Q(col_id[3]));
   DFCNQD1BWP col_id_reg_4_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN63_n72),
	.Q(col_id[4]));
   DFCNQD1BWP col_id_reg_5_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN56_n73),
	.Q(col_id[5]));
   DFCNQD1BWP col_id_reg_6_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n74),
	.Q(col_id[6]));
   DFCNQD1BWP col_id_reg_7_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n75),
	.Q(col_id[7]));
   DFCNQD1BWP col_id_reg_8_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN64_n76),
	.Q(col_id[8]));
   DFCNQD1BWP row_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n88),
	.Q(row_id[0]));
   DFCNQD1BWP row_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n87),
	.Q(row_id[1]));
   DFCNQD1BWP row_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n86),
	.Q(row_id[2]));
   DFCNQD1BWP rd_row_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n840),
	.Q(rd_row_id[2]));
   DFCNQD1BWP rd_row_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n830),
	.Q(rd_row_id[1]));
   DFCNQD1BWP rd_row_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n820),
	.Q(rd_row_id[0]));
   DFCNQD1BWP rd_row_id_d1_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN36_rd_row_id_2),
	.Q(rd_row_id_d1[2]));
   DFCNQD1BWP rd_row_id_d1_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN33_rd_row_id_1),
	.Q(rd_row_id_d1[1]));
   DFCNQD1BWP rd_row_id_d1_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN41_rd_row_id_0),
	.Q(rd_row_id_d1[0]));
   DFCNQD1BWP phase_col_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1170),
	.Q(phase_col_id[0]));
   DFCNQD1BWP dl_cur_state_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN55_dl_next_state),
	.Q(dl_cur_state));
   DFCNQD1BWP phase_col_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN58_n118),
	.Q(phase_col_id[1]));
   DFCNQD1BWP phase_col_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN60_n1190),
	.Q(phase_col_id[2]));
   DFCNQD1BWP phase_col_id_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN67_n120),
	.Q(phase_col_id[3]));
   DFCNQD1BWP phase_col_id_reg_4_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN62_n1210),
	.Q(phase_col_id[4]));
   DFCNQD1BWP phase_row_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n82),
	.Q(phase_row_id[0]));
   DFCNQD1BWP phase_row_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n81),
	.Q(phase_row_id[1]));
   DFCNQD1BWP phase_row_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n80),
	.Q(phase_row_id[2]));
   DFCNQD1BWP dl_cur_state_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN50_dl_cur_state),
	.Q(FE_PHN38_dl_cur_state_d1));
   DFCNQD1BWP dl_cur_state_d2_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(dl_cur_state_d1),
	.Q(dl_cur_state_d2));
   DFCNQD1BWP phase_row_id_d1_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN43_phase_row_id_2),
	.Q(phase_row_id_d1[2]));
   DFCNQD1BWP phase_row_id_d2_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN34_phase_row_id_d1_2),
	.Q(phase_row_id_d2[2]));
   DFCNQD1BWP phase_row_id_d1_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN52_phase_row_id_1),
	.Q(phase_row_id_d1[1]));
   DFCNQD1BWP phase_row_id_d2_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN37_phase_row_id_d1_1),
	.Q(phase_row_id_d2[1]));
   DFCNQD1BWP phase_row_id_d1_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN45_phase_row_id_0),
	.Q(phase_row_id_d1[0]));
   DFCNQD1BWP phase_row_id_d2_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN35_phase_row_id_d1_0),
	.Q(phase_row_id_d2[0]));
   DFCNQD1BWP ul_cur_state_d1_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n79),
	.Q(ul_cur_state_d1_0_));
   DFCNQD1BWP wr_data_in_g_d2_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN39_wr_data_in_g_d1),
	.Q(FE_OFN25_wr_data_in_g_d2));
   DFCNQD1BWP rd_data_out_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n90),
	.Q(FE_OFN27_rd_data_out_g));
   DFCNQD1BWP rd_vld_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n870),
	.Q(FE_OFN26_rd_vld_g));
   DFCNQD1BWP p_code_vld_bus_reg_7_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1290),
	.Q(FE_OFN16_p_code_vld_bus_7));
   DFCNQD1BWP p_code_vld_bus_reg_6_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n128),
	.Q(FE_OFN17_p_code_vld_bus_6));
   DFCNQD1BWP p_code_vld_bus_reg_5_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1270),
	.Q(FE_OFN18_p_code_vld_bus_5));
   DFCNQD1BWP p_code_vld_bus_reg_4_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n126),
	.Q(FE_OFN19_p_code_vld_bus_4));
   DFCNQD1BWP p_code_vld_bus_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1250),
	.Q(FE_OFN20_p_code_vld_bus_3));
   DFCNQD1BWP p_code_vld_bus_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n124),
	.Q(FE_OFN21_p_code_vld_bus_2));
   DFCNQD1BWP p_code_vld_bus_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1230),
	.Q(FE_OFN22_p_code_vld_bus_1));
   DFCNQD1BWP p_code_vld_bus_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n122),
	.Q(FE_OFN23_p_code_vld_bus_0));
   DFCNQD1BWP p_out_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n134),
	.Q(FE_OFN29_p_out_g));
   DFCNQD1BWP p_out_vld_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n132),
	.Q(FE_OFN28_p_out_vld_g));
   DFCNQD1BWP wr_vld_bus_reg_7_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1490),
	.Q(FE_OFN0_wr_vld_bus_7));
   DFCNQD1BWP wr_vld_bus_reg_6_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_OFN30_n1470),
	.Q(FE_OFN1_wr_vld_bus_6));
   DFCNQD1BWP wr_vld_bus_reg_5_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1450),
	.Q(FE_OFN2_wr_vld_bus_5));
   DFCNQD1BWP wr_vld_bus_reg_4_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1430),
	.Q(FE_OFN3_wr_vld_bus_4));
   DFCNQD1BWP wr_vld_bus_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1410),
	.Q(FE_OFN4_wr_vld_bus_3));
   DFCNQD1BWP wr_vld_bus_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1390),
	.Q(FE_OFN5_wr_vld_bus_2));
   DFCNQD1BWP wr_vld_bus_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1370),
	.Q(FE_OFN6_wr_vld_bus_1));
   DFCNQD1BWP wr_vld_bus_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1350),
	.Q(FE_OFN7_wr_vld_bus_0));
   DFCNQD1BWP rd_rdy_bus_reg_7_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1500),
	.Q(FE_OFN8_rd_rdy_bus_7));
   DFCNQD1BWP rd_rdy_bus_reg_6_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n148),
	.Q(FE_OFN9_rd_rdy_bus_6));
   DFCNQD1BWP rd_rdy_bus_reg_5_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n146),
	.Q(FE_OFN10_rd_rdy_bus_5));
   DFCNQD1BWP rd_rdy_bus_reg_4_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n144),
	.Q(FE_OFN11_rd_rdy_bus_4));
   DFCNQD1BWP rd_rdy_bus_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n142),
	.Q(FE_OFN12_rd_rdy_bus_3));
   DFCNQD1BWP rd_rdy_bus_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n140),
	.Q(FE_OFN13_rd_rdy_bus_2));
   DFCNQD1BWP rd_rdy_bus_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n138),
	.Q(FE_OFN14_rd_rdy_bus_1));
   DFCNQD1BWP rd_rdy_bus_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n136),
	.Q(FE_OFN15_rd_rdy_bus_0));
   DFCNQD1BWP couple_en_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n83),
	.Q(FE_OFN24_couple_en));
   IND2D0BWP U137 (.A1(couple_en),
	.B1(n239),
	.ZN(n83));
   INVD0BWP U198 (.I(n246),
	.ZN(n173));
   TIEHBWP U199 (.Z(n79));
   CKND2D1BWP U200 (.A1(ul_cur_state[0]),
	.A2(ul_cur_state[1]),
	.ZN(n239));
   INVD0BWP U201 (.I(row_id[2]),
	.ZN(n189));
   NR2D1BWP U202 (.A1(n239),
	.A2(n189),
	.ZN(n840));
   INVD0BWP U203 (.I(FE_PHN50_dl_cur_state),
	.ZN(n155));
   NR2D0BWP U204 (.A1(n155),
	.A2(FE_PHN51_phase_col_id_0),
	.ZN(n1170));
   INVD0BWP U205 (.I(ul_cur_state[0]),
	.ZN(n186));
   NR2D0BWP U206 (.A1(FE_PHN68_n186),
	.A2(FE_PHN42_col_id_0),
	.ZN(n68));
   CKND2D0BWP U207 (.A1(phase_row_id[2]),
	.A2(FE_PHN52_phase_row_id_1),
	.ZN(n156));
   CKND2D0BWP U208 (.A1(phase_row_id[0]),
	.A2(dl_cur_state),
	.ZN(n245));
   NR2D0BWP U209 (.A1(n156),
	.A2(n245),
	.ZN(n1290));
   NR2D0BWP U210 (.A1(n155),
	.A2(phase_row_id[0]),
	.ZN(n162));
   INVD0BWP U211 (.I(n162),
	.ZN(n243));
   NR2D0BWP U212 (.A1(n156),
	.A2(n243),
	.ZN(n128));
   OR2D0BWP U213 (.A1(n245),
	.A2(FE_PHN69_phase_row_id_1),
	.Z(n172));
   NR2XD1BWP U214 (.A1(n172),
	.A2(phase_row_id[2]),
	.ZN(n1230));
   INVD0BWP U215 (.I(phase_row_id[2]),
	.ZN(n247));
   NR2D0BWP U216 (.A1(n247),
	.A2(n172),
	.ZN(n1270));
   INVD0BWP U217 (.I(FE_PHN52_phase_row_id_1),
	.ZN(n244));
   CKND2D0BWP U218 (.A1(n162),
	.A2(n244),
	.ZN(n149));
   NR2D2BWP U219 (.A1(n149),
	.A2(phase_row_id[2]),
	.ZN(n122));
   NR2D0BWP U220 (.A1(n149),
	.A2(n247),
	.ZN(n126));
   NR2D0BWP U221 (.A1(n186),
	.A2(ul_cur_state[1]),
	.ZN(n151));
   CKND2D0BWP U222 (.A1(n151),
	.A2(n189),
	.ZN(n240));
   CKND2D1BWP U223 (.A1(row_id[1]),
	.A2(row_id[0]),
	.ZN(n190));
   NR2D0BWP U224 (.A1(n240),
	.A2(n190),
	.ZN(n1410));
   INVD0BWP U225 (.I(row_id[0]),
	.ZN(n182));
   INVD0BWP U226 (.I(row_id[1]),
	.ZN(n242));
   CKND2D1BWP U227 (.A1(n182),
	.A2(n242),
	.ZN(n238));
   NR2D0BWP U228 (.A1(n240),
	.A2(n238),
	.ZN(n1350));
   CKND2D1BWP U229 (.A1(row_id[0]),
	.A2(n242),
	.ZN(n184));
   NR2D0BWP U230 (.A1(n240),
	.A2(n184),
	.ZN(n1370));
   INVD0BWP U231 (.I(n840),
	.ZN(n150));
   NR2D0BWP U232 (.A1(n150),
	.A2(n184),
	.ZN(n146));
   NR2D0BWP U233 (.A1(n150),
	.A2(n238),
	.ZN(n144));
   CKND2D1BWP U234 (.A1(row_id[2]),
	.A2(n151),
	.ZN(n241));
   NR2D2BWP U235 (.A1(n241),
	.A2(n190),
	.ZN(n1490));
   NR2D0BWP U236 (.A1(n241),
	.A2(n238),
	.ZN(n1430));
   NR2D0BWP U237 (.A1(n241),
	.A2(n184),
	.ZN(n1450));
   NR2D0BWP U238 (.A1(n239),
	.A2(n182),
	.ZN(n820));
   AN3D0BWP U239 (.A1(n820),
	.A2(n242),
	.A3(n189),
	.Z(n138));
   NR2D0BWP U240 (.A1(n239),
	.A2(n242),
	.ZN(n830));
   CKND2D0BWP U241 (.A1(n830),
	.A2(n189),
	.ZN(n152));
   NR2D0BWP U242 (.A1(n152),
	.A2(n182),
	.ZN(n142));
   NR2D0BWP U243 (.A1(n152),
	.A2(FE_PHN40_row_id_0),
	.ZN(n140));
   CKND2D0BWP U244 (.A1(row_id[2]),
	.A2(n830),
	.ZN(n153));
   NR2D2BWP U245 (.A1(n153),
	.A2(FE_PHN40_row_id_0),
	.ZN(n148));
   NR2D2BWP U246 (.A1(n153),
	.A2(n182),
	.ZN(n1500));
   INVD0BWP U247 (.I(phase_col_id[3]),
	.ZN(n154));
   CKND2D0BWP U248 (.A1(FE_PHN51_phase_col_id_0),
	.A2(phase_col_id[1]),
	.ZN(n161));
   INVD0BWP U249 (.I(n161),
	.ZN(n160));
   CKND2D0BWP U250 (.A1(n160),
	.A2(phase_col_id[2]),
	.ZN(n159));
   NR2D0BWP U251 (.A1(n159),
	.A2(n154),
	.ZN(n166));
   IND4D0BWP U252 (.A1(phase_col_id[2]),
	.B1(n154),
	.B2(n160),
	.B3(phase_col_id[4]),
	.ZN(n157));
   CKND2D0BWP U253 (.A1(dl_cur_state),
	.A2(n157),
	.ZN(n246));
   AOI211D0BWP U254 (.A1(n154),
	.A2(n159),
	.B(n166),
	.C(n246),
	.ZN(n120));
   CKND2D0BWP U255 (.A1(p_en_d2),
	.A2(n155),
	.ZN(n158));
   INVD0BWP U256 (.I(FE_PHN45_phase_row_id_0),
	.ZN(n163));
   OAI31D0BWP U257 (.A1(n163),
	.A2(n157),
	.A3(n156),
	.B(FE_PHN50_dl_cur_state),
	.ZN(n248));
   OAI21D0BWP U258 (.A1(p_en_d1),
	.A2(n158),
	.B(n248),
	.ZN(dl_next_state));
   OA211D0BWP U259 (.A1(n160),
	.A2(phase_col_id[2]),
	.B(n173),
	.C(n159),
	.Z(n1190));
   OA211D0BWP U260 (.A1(FE_PHN51_phase_col_id_0),
	.A2(phase_col_id[1]),
	.B(n173),
	.C(n161),
	.Z(n118));
   NR2D0BWP U261 (.A1(n173),
	.A2(n162),
	.ZN(n171));
   AOI21D0BWP U262 (.A1(n173),
	.A2(n163),
	.B(n171),
	.ZN(n82));
   INVD0BWP U263 (.I(phase_col_id[4]),
	.ZN(n165));
   INVD0BWP U264 (.I(n166),
	.ZN(n164));
   AOI221D0BWP U265 (.A1(phase_col_id[4]),
	.A2(n166),
	.B1(n165),
	.B2(n164),
	.C(n246),
	.ZN(n1210));
   IND4D0BWP U266 (.A1(col_id[2]),
	.B1(col_id[8]),
	.B2(col_id[5]),
	.B3(col_id[7]),
	.ZN(n168));
   CKND2D0BWP U267 (.A1(col_id[0]),
	.A2(col_id[1]),
	.ZN(n169));
   OR4D0BWP U268 (.A1(col_id[3]),
	.A2(col_id[4]),
	.A3(col_id[6]),
	.A4(n169),
	.Z(n167));
   NR2XD0BWP U269 (.A1(n168),
	.A2(n167),
	.ZN(n183));
   NR2D0BWP U270 (.A1(n186),
	.A2(n183),
	.ZN(n195));
   OA211D0BWP U271 (.A1(FE_PHN42_col_id_0),
	.A2(col_id[1]),
	.B(FE_OFN31_n195),
	.C(n169),
	.Z(n69));
   INVD0BWP U272 (.I(n169),
	.ZN(n170));
   CKND2D0BWP U273 (.A1(col_id[2]),
	.A2(n170),
	.ZN(n175));
   INVD0BWP U274 (.I(col_id[3]),
	.ZN(n176));
   NR2D0BWP U275 (.A1(n175),
	.A2(n176),
	.ZN(n174));
   CKND2D0BWP U276 (.A1(col_id[4]),
	.A2(n174),
	.ZN(n177));
   OA211D0BWP U277 (.A1(col_id[4]),
	.A2(n174),
	.B(FE_OFN31_n195),
	.C(n177),
	.Z(n72));
   OA211D0BWP U278 (.A1(col_id[2]),
	.A2(n170),
	.B(FE_OFN31_n195),
	.C(n175),
	.Z(n70));
   OAI22D0BWP U279 (.A1(n173),
	.A2(n172),
	.B1(n171),
	.B2(n244),
	.ZN(n81));
   INVD0BWP U280 (.I(FE_OFN31_n195),
	.ZN(n192));
   AOI211D0BWP U281 (.A1(n176),
	.A2(n175),
	.B(n174),
	.C(n192),
	.ZN(n71));
   INVD0BWP U282 (.I(col_id[5]),
	.ZN(n178));
   NR2D0BWP U283 (.A1(n177),
	.A2(n178),
	.ZN(n188));
   AOI211D0BWP U284 (.A1(n178),
	.A2(n177),
	.B(n188),
	.C(n192),
	.ZN(n73));
   INVD0BWP U285 (.I(FE_PHN32_ul_cur_state_1),
	.ZN(n180));
   OAI21D0BWP U286 (.A1(FE_PHN46_ul_cur_state_0),
	.A2(en_g_d1),
	.B(n180),
	.ZN(n179));
   IND3D0BWP U287 (.A1(n190),
	.B1(n183),
	.B2(FE_PHN48_row_id_2),
	.ZN(n181));
   CKND2D0BWP U288 (.A1(FE_PHN46_ul_cur_state_0),
	.A2(n181),
	.ZN(n191));
   CKND2D0BWP U289 (.A1(n179),
	.A2(n191),
	.ZN(n85));
   AOI21D0BWP U290 (.A1(n181),
	.A2(n180),
	.B(n186),
	.ZN(n84));
   AOI21D0BWP U291 (.A1(FE_PHN46_ul_cur_state_0),
	.A2(n182),
	.B(FE_OFN31_n195),
	.ZN(n187));
   AOI21D0BWP U292 (.A1(FE_OFN31_n195),
	.A2(n182),
	.B(n187),
	.ZN(n88));
   IND2D0BWP U293 (.A1(n184),
	.B1(n183),
	.ZN(n185));
   OAI22D0BWP U294 (.A1(n187),
	.A2(n242),
	.B1(n186),
	.B2(n185),
	.ZN(n87));
   CKND2D0BWP U295 (.A1(FE_PHN47_col_id_6),
	.A2(n188),
	.ZN(n193));
   OA211D0BWP U296 (.A1(FE_PHN47_col_id_6),
	.A2(n188),
	.B(FE_OFN31_n195),
	.C(n193),
	.Z(n74));
   OAI32D0BWP U297 (.A1(n191),
	.A2(FE_OFN31_n195),
	.A3(n190),
	.B1(n189),
	.B2(n191),
	.ZN(n86));
   INVD0BWP U298 (.I(col_id[7]),
	.ZN(n194));
   NR2D0BWP U299 (.A1(n193),
	.A2(n194),
	.ZN(n197));
   AOI211D0BWP U300 (.A1(FE_PHN44_n194),
	.A2(n193),
	.B(n197),
	.C(n192),
	.ZN(n75));
   OAI21D0BWP U301 (.A1(col_id[8]),
	.A2(n197),
	.B(FE_OFN31_n195),
	.ZN(n196));
   AOI21D0BWP U302 (.A1(col_id[8]),
	.A2(n197),
	.B(n196),
	.ZN(n76));
   INVD0BWP U303 (.I(rd_row_id_d1[1]),
	.ZN(n199));
   NR2D0BWP U304 (.A1(n199),
	.A2(rd_row_id_d1[2]),
	.ZN(n227));
   AOI21D0BWP U305 (.A1(n227),
	.A2(rd_data_out_bus[2]),
	.B(rd_row_id_d1[0]),
	.ZN(n206));
   NR2D0BWP U306 (.A1(rd_row_id_d1[2]),
	.A2(rd_row_id_d1[1]),
	.ZN(n229));
   INVD0BWP U307 (.I(rd_row_id_d1[2]),
	.ZN(n198));
   NR2D0BWP U308 (.A1(n198),
	.A2(rd_row_id_d1[1]),
	.ZN(n228));
   AOI22D0BWP U309 (.A1(n229),
	.A2(rd_data_out_bus[0]),
	.B1(n228),
	.B2(rd_data_out_bus[4]),
	.ZN(n205));
   NR2D0BWP U310 (.A1(n199),
	.A2(n198),
	.ZN(n233));
   CKND2D0BWP U311 (.A1(n233),
	.A2(rd_data_out_bus[6]),
	.ZN(n204));
   CKND2D0BWP U312 (.A1(n227),
	.A2(rd_data_out_bus[3]),
	.ZN(n201));
   AOI22D0BWP U313 (.A1(n229),
	.A2(rd_data_out_bus[1]),
	.B1(n228),
	.B2(rd_data_out_bus[5]),
	.ZN(n200));
   ND3D0BWP U314 (.A1(n201),
	.A2(n200),
	.A3(rd_row_id_d1[0]),
	.ZN(n202));
   AOI32D0BWP U315 (.A1(n233),
	.A2(ul_cur_state_d1_0_),
	.A3(rd_data_out_bus[7]),
	.B1(n202),
	.B2(ul_cur_state_d1_0_),
	.ZN(n203));
   AOI31D2BWP U316 (.A1(n206),
	.A2(n205),
	.A3(n204),
	.B(n203),
	.ZN(FE_PHN54_n90));
   INVD0BWP U317 (.I(phase_row_id_d2[1]),
	.ZN(n208));
   NR2D0BWP U318 (.A1(n208),
	.A2(phase_row_id_d2[2]),
	.ZN(n216));
   AOI21D0BWP U319 (.A1(n216),
	.A2(p_out_bus[2]),
	.B(phase_row_id_d2[0]),
	.ZN(n215));
   NR2D0BWP U320 (.A1(phase_row_id_d2[2]),
	.A2(phase_row_id_d2[1]),
	.ZN(n218));
   INVD0BWP U321 (.I(phase_row_id_d2[2]),
	.ZN(n207));
   NR2D0BWP U322 (.A1(n207),
	.A2(phase_row_id_d2[1]),
	.ZN(n217));
   AOI22D0BWP U323 (.A1(n218),
	.A2(p_out_bus[0]),
	.B1(n217),
	.B2(p_out_bus[4]),
	.ZN(n214));
   NR2D0BWP U324 (.A1(n208),
	.A2(n207),
	.ZN(n222));
   CKND2D0BWP U325 (.A1(n222),
	.A2(p_out_bus[6]),
	.ZN(n213));
   CKND2D0BWP U326 (.A1(n216),
	.A2(p_out_bus[3]),
	.ZN(n210));
   AOI22D0BWP U327 (.A1(n218),
	.A2(p_out_bus[1]),
	.B1(n217),
	.B2(p_out_bus[5]),
	.ZN(n209));
   ND3D0BWP U328 (.A1(n210),
	.A2(n209),
	.A3(phase_row_id_d2[0]),
	.ZN(n211));
   AOI32D0BWP U329 (.A1(n222),
	.A2(dl_cur_state_d2),
	.A3(p_out_bus[7]),
	.B1(n211),
	.B2(dl_cur_state_d2),
	.ZN(n212));
   AOI31D2BWP U330 (.A1(n215),
	.A2(n214),
	.A3(n213),
	.B(n212),
	.ZN(n134));
   AOI21D0BWP U331 (.A1(n216),
	.A2(p_out_vld_bus[2]),
	.B(phase_row_id_d2[0]),
	.ZN(n226));
   AOI22D0BWP U332 (.A1(n218),
	.A2(p_out_vld_bus[0]),
	.B1(n217),
	.B2(p_out_vld_bus[4]),
	.ZN(n225));
   CKND2D0BWP U333 (.A1(n222),
	.A2(p_out_vld_bus[6]),
	.ZN(n224));
   CKND2D0BWP U334 (.A1(n216),
	.A2(p_out_vld_bus[3]),
	.ZN(n220));
   AOI22D0BWP U335 (.A1(n218),
	.A2(p_out_vld_bus[1]),
	.B1(n217),
	.B2(p_out_vld_bus[5]),
	.ZN(n219));
   ND3D0BWP U336 (.A1(n220),
	.A2(n219),
	.A3(phase_row_id_d2[0]),
	.ZN(n221));
   AOI32D0BWP U337 (.A1(n222),
	.A2(dl_cur_state_d2),
	.A3(p_out_vld_bus[7]),
	.B1(n221),
	.B2(dl_cur_state_d2),
	.ZN(n223));
   AOI31D2BWP U338 (.A1(n226),
	.A2(n225),
	.A3(n224),
	.B(n223),
	.ZN(n132));
   AOI21D0BWP U339 (.A1(n227),
	.A2(rd_vld_bus[2]),
	.B(rd_row_id_d1[0]),
	.ZN(n237));
   AOI22D0BWP U340 (.A1(n229),
	.A2(rd_vld_bus[0]),
	.B1(n228),
	.B2(rd_vld_bus[4]),
	.ZN(n236));
   CKND2D0BWP U341 (.A1(n233),
	.A2(rd_vld_bus[6]),
	.ZN(n235));
   CKND2D0BWP U342 (.A1(n227),
	.A2(rd_vld_bus[3]),
	.ZN(n231));
   AOI22D0BWP U343 (.A1(n229),
	.A2(rd_vld_bus[1]),
	.B1(n228),
	.B2(rd_vld_bus[5]),
	.ZN(n230));
   ND3D0BWP U344 (.A1(n231),
	.A2(n230),
	.A3(rd_row_id_d1[0]),
	.ZN(n232));
   AOI32D0BWP U345 (.A1(n233),
	.A2(ul_cur_state_d1_0_),
	.A3(rd_vld_bus[7]),
	.B1(n232),
	.B2(ul_cur_state_d1_0_),
	.ZN(n234));
   AOI31D2BWP U346 (.A1(n237),
	.A2(n236),
	.A3(n235),
	.B(n234),
	.ZN(FE_PHN53_n870));
   NR3D0BWP U347 (.A1(FE_PHN48_row_id_2),
	.A2(n239),
	.A3(n238),
	.ZN(n136));
   NR3D0BWP U348 (.A1(FE_PHN40_row_id_0),
	.A2(n242),
	.A3(n240),
	.ZN(n1390));
   NR3D0BWP U349 (.A1(row_id[0]),
	.A2(n242),
	.A3(n241),
	.ZN(n1470));
   NR3D1BWP U350 (.A1(phase_row_id[2]),
	.A2(n243),
	.A3(n244),
	.ZN(n124));
   NR3D0BWP U351 (.A1(n245),
	.A2(phase_row_id[2]),
	.A3(n244),
	.ZN(n1250));
   MOAI22D0BWP U352 (.A1(n248),
	.A2(n247),
	.B1(n1250),
	.B2(n246),
	.ZN(n80));
endmodule

