/*
###############################################################
#  Generated by:      Cadence Innovus 19.12-s087_1
#  OS:                Linux x86_64(Host ID pdk5)
#  Generated on:      Tue Apr 28 17:05:06 2026
#  Design:            global_ctrl
#  Command:           saveNetlist ./output/global_ctrl/global_ctrl_enc.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : S-2021.06-SP1
// Date      : Tue Apr 28 16:37:53 2026
/////////////////////////////////////////////////////////////
module global_ctrl (
	clk, 
	rstn, 
	p_en, 
	en_g, 
	wr_data_in_g, 
	rd_vld_bus, 
	rd_data_out_bus, 
	p_out_vld_bus, 
	p_out_bus, 
	couple_en, 
	wr_data_in_g_d2, 
	rd_vld_g, 
	rd_data_out_g, 
	wr_vld_bus, 
	rd_rdy_bus, 
	p_code_vld_bus, 
	p_out_vld_g, 
	p_out_g);
   input clk;
   input rstn;
   input p_en;
   input en_g;
   input wr_data_in_g;
   input [7:0] rd_vld_bus;
   input [7:0] rd_data_out_bus;
   input [7:0] p_out_vld_bus;
   input [7:0] p_out_bus;
   output couple_en;
   output wr_data_in_g_d2;
   output rd_vld_g;
   output rd_data_out_g;
   output [7:0] wr_vld_bus;
   output [7:0] rd_rdy_bus;
   output [7:0] p_code_vld_bus;
   output p_out_vld_g;
   output p_out_g;

   // Internal wires
   wire FE_PHN71_col_id_6;
   wire FE_PHN70_n1320;
   wire FE_PHN69_n177;
   wire FE_PHN68_n133;
   wire FE_PHN67_n131;
   wire FE_PHN66_n129;
   wire FE_PHN65_n820;
   wire FE_PHN64_n1300;
   wire FE_PHN63_n1280;
   wire FE_PHN62_n127;
   wire FE_PHN61_dl_next_state;
   wire FE_PHN60_col_id_2;
   wire FE_PHN59_col_id_4;
   wire FE_PHN58_n93;
   wire FE_PHN57_dl_cur_state;
   wire FE_PHN56_col_id_6;
   wire FE_PHN55_row_id_2;
   wire FE_PHN54_p_en_d1;
   wire FE_PHN53_col_id_8;
   wire FE_PHN52_col_id_0;
   wire FE_PHN51_phase_row_id_0;
   wire FE_PHN50_n208;
   wire FE_PHN49_n182;
   wire FE_PHN48_n187;
   wire FE_PHN47_n185;
   wire FE_PHN46_FE_OFN25_couple_en;
   wire FE_PHN45_phase_row_id_1;
   wire FE_PHN44_n204;
   wire FE_PHN43_dl_cur_state_d1;
   wire FE_PHN42_rd_row_id_1;
   wire FE_PHN41_phase_row_id_d1_1;
   wire FE_PHN40_ul_cur_state_1;
   wire FE_PHN39_phase_row_id_d1_2;
   wire FE_PHN38_rd_row_id_0;
   wire FE_PHN37_rd_row_id_2;
   wire FE_PHN36_wr_data_in_g_d1;
   wire FE_PHN35_phase_row_id_d1_0;
   wire FE_PHN34_phase_row_id_2;
   wire FE_PHN33_row_id_0;
   wire CTS_1;
   wire FE_OFN32_n1610;
   wire FE_OFN31_n1590;
   wire FE_OFN30_p_out_g;
   wire FE_OFN29_p_out_vld_g;
   wire FE_OFN28_rd_data_out_g;
   wire FE_OFN27_rd_vld_g;
   wire FE_OFN26_wr_data_in_g_d2;
   wire FE_OFN25_couple_en;
   wire FE_OFN24_rstn;
   wire FE_OFN23_p_code_vld_bus_0;
   wire FE_OFN22_p_code_vld_bus_1;
   wire FE_OFN21_p_code_vld_bus_2;
   wire FE_OFN20_p_code_vld_bus_3;
   wire FE_OFN19_p_code_vld_bus_4;
   wire FE_OFN18_p_code_vld_bus_5;
   wire FE_OFN17_p_code_vld_bus_6;
   wire FE_OFN16_p_code_vld_bus_7;
   wire FE_OFN15_rd_rdy_bus_0;
   wire FE_OFN14_rd_rdy_bus_1;
   wire FE_OFN13_rd_rdy_bus_2;
   wire FE_OFN12_rd_rdy_bus_3;
   wire FE_OFN11_rd_rdy_bus_4;
   wire FE_OFN10_rd_rdy_bus_5;
   wire FE_OFN9_rd_rdy_bus_6;
   wire FE_OFN8_rd_rdy_bus_7;
   wire FE_OFN7_wr_vld_bus_0;
   wire FE_OFN6_wr_vld_bus_1;
   wire FE_OFN5_wr_vld_bus_2;
   wire FE_OFN4_wr_vld_bus_3;
   wire FE_OFN3_wr_vld_bus_4;
   wire FE_OFN2_wr_vld_bus_5;
   wire FE_OFN1_wr_vld_bus_6;
   wire FE_OFN0_wr_vld_bus_7;
   wire en_g_d1;
   wire wr_data_in_g_d1;
   wire p_en_d1;
   wire p_en_d2;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n800;
   wire n810;
   wire n820;
   wire n880;
   wire n890;
   wire n900;
   wire ul_cur_state_d1_0_;
   wire n93;
   wire n960;
   wire dl_cur_state;
   wire dl_next_state;
   wire n127;
   wire n1280;
   wire n129;
   wire n1300;
   wire n131;
   wire n1320;
   wire n133;
   wire n1340;
   wire n135;
   wire n1360;
   wire n137;
   wire n1380;
   wire n139;
   wire n1400;
   wire n141;
   wire dl_cur_state_d1;
   wire dl_cur_state_d2;
   wire n1440;
   wire n1460;
   wire n147;
   wire n1480;
   wire n149;
   wire n1500;
   wire n1510;
   wire n1520;
   wire n1530;
   wire n1540;
   wire n1550;
   wire n1560;
   wire n1570;
   wire n1580;
   wire n1590;
   wire n1600;
   wire n1610;
   wire n1620;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire [1:0] ul_cur_state;
   wire [10:0] col_id;
   wire [2:0] row_id;
   wire [2:0] rd_row_id;
   wire [2:0] rd_row_id_d1;
   wire [6:0] phase_col_id;
   wire [2:0] phase_row_id;
   wire [2:0] phase_row_id_d1;
   wire [2:0] phase_row_id_d2;

   CKBD1BWP FE_PHC71_col_id_6 (.I(FE_PHN56_col_id_6),
	.Z(FE_PHN71_col_id_6));
   DEL050D1BWP FE_PHC70_n1320 (.I(FE_PHN70_n1320),
	.Z(n1320));
   CKBD1BWP FE_PHC69_n177 (.I(n177),
	.Z(FE_PHN69_n177));
   DEL100D1BWP FE_PHC68_n133 (.I(n133),
	.Z(FE_PHN68_n133));
   DEL050D1BWP FE_PHC67_n131 (.I(n131),
	.Z(FE_PHN67_n131));
   DEL050D1BWP FE_PHC66_n129 (.I(n129),
	.Z(FE_PHN66_n129));
   DEL100D1BWP FE_PHC65_n820 (.I(n820),
	.Z(FE_PHN65_n820));
   DEL050D1BWP FE_PHC64_n1300 (.I(n1300),
	.Z(FE_PHN64_n1300));
   DEL050D1BWP FE_PHC63_n1280 (.I(n1280),
	.Z(FE_PHN63_n1280));
   DEL100D1BWP FE_PHC62_n127 (.I(n127),
	.Z(FE_PHN62_n127));
   DEL050D1BWP FE_PHC61_dl_next_state (.I(dl_next_state),
	.Z(FE_PHN61_dl_next_state));
   DEL050D1BWP FE_PHC60_col_id_2 (.I(col_id[2]),
	.Z(FE_PHN60_col_id_2));
   DEL050D1BWP FE_PHC59_col_id_4 (.I(col_id[4]),
	.Z(FE_PHN59_col_id_4));
   BUFFD1BWP FE_PHC58_n93 (.I(FE_PHN58_n93),
	.Z(n93));
   DEL100D1BWP FE_PHC57_dl_cur_state (.I(dl_cur_state),
	.Z(FE_PHN57_dl_cur_state));
   CKBD0BWP FE_PHC56_col_id_6 (.I(col_id[6]),
	.Z(FE_PHN56_col_id_6));
   DEL050D1BWP FE_PHC55_row_id_2 (.I(row_id[2]),
	.Z(FE_PHN55_row_id_2));
   BUFFD1BWP FE_PHC54_p_en_d1 (.I(p_en_d1),
	.Z(FE_PHN54_p_en_d1));
   DEL050D1BWP FE_PHC53_col_id_8 (.I(col_id[8]),
	.Z(FE_PHN53_col_id_8));
   CKBD1BWP FE_PHC52_col_id_0 (.I(col_id[0]),
	.Z(FE_PHN52_col_id_0));
   DEL100D1BWP FE_PHC51_phase_row_id_0 (.I(phase_row_id[0]),
	.Z(FE_PHN51_phase_row_id_0));
   DEL050D1BWP FE_PHC50_n208 (.I(n208),
	.Z(FE_PHN50_n208));
   DEL050D1BWP FE_PHC49_n182 (.I(n182),
	.Z(FE_PHN49_n182));
   DEL050D1BWP FE_PHC48_n187 (.I(n187),
	.Z(FE_PHN48_n187));
   DEL050D1BWP FE_PHC47_n185 (.I(n185),
	.Z(FE_PHN47_n185));
   DEL050D1BWP FE_PHC46_FE_OFN25_couple_en (.I(FE_OFN25_couple_en),
	.Z(FE_PHN46_FE_OFN25_couple_en));
   DEL175D1BWP FE_PHC45_phase_row_id_1 (.I(phase_row_id[1]),
	.Z(FE_PHN45_phase_row_id_1));
   DEL050D1BWP FE_PHC44_n204 (.I(n204),
	.Z(FE_PHN44_n204));
   DEL125D1BWP FE_PHC43_dl_cur_state_d1 (.I(dl_cur_state_d1),
	.Z(FE_PHN43_dl_cur_state_d1));
   DEL125D1BWP FE_PHC42_rd_row_id_1 (.I(rd_row_id[1]),
	.Z(FE_PHN42_rd_row_id_1));
   DEL125D1BWP FE_PHC41_phase_row_id_d1_1 (.I(phase_row_id_d1[1]),
	.Z(FE_PHN41_phase_row_id_d1_1));
   DEL050D1BWP FE_PHC40_ul_cur_state_1 (.I(ul_cur_state[1]),
	.Z(FE_PHN40_ul_cur_state_1));
   DEL125D1BWP FE_PHC39_phase_row_id_d1_2 (.I(phase_row_id_d1[2]),
	.Z(FE_PHN39_phase_row_id_d1_2));
   DEL125D1BWP FE_PHC38_rd_row_id_0 (.I(FE_PHN38_rd_row_id_0),
	.Z(rd_row_id[0]));
   DEL125D1BWP FE_PHC37_rd_row_id_2 (.I(rd_row_id[2]),
	.Z(FE_PHN37_rd_row_id_2));
   DEL125D1BWP FE_PHC36_wr_data_in_g_d1 (.I(wr_data_in_g_d1),
	.Z(FE_PHN36_wr_data_in_g_d1));
   DEL100D1BWP FE_PHC35_phase_row_id_d1_0 (.I(phase_row_id_d1[0]),
	.Z(FE_PHN35_phase_row_id_d1_0));
   DEL050D1BWP FE_PHC34_phase_row_id_2 (.I(phase_row_id[2]),
	.Z(FE_PHN34_phase_row_id_2));
   CKBD0BWP FE_PHC33_row_id_0 (.I(row_id[0]),
	.Z(FE_PHN33_row_id_0));
   BUFFD20BWP CTS_ccl_a_buf_00003 (.I(clk),
	.Z(CTS_1));
   CKBD1BWP FE_OFC32_n1610 (.I(n1610),
	.Z(FE_OFN32_n1610));
   CKBD1BWP FE_OFC31_n1590 (.I(n1590),
	.Z(FE_OFN31_n1590));
   CKBD8BWP FE_OFC30_p_out_g (.I(FE_OFN30_p_out_g),
	.Z(p_out_g));
   CKBD8BWP FE_OFC29_p_out_vld_g (.I(FE_OFN29_p_out_vld_g),
	.Z(p_out_vld_g));
   CKBD8BWP FE_OFC28_rd_data_out_g (.I(FE_OFN28_rd_data_out_g),
	.Z(rd_data_out_g));
   CKBD8BWP FE_OFC27_rd_vld_g (.I(FE_OFN27_rd_vld_g),
	.Z(rd_vld_g));
   CKBD8BWP FE_OFC26_wr_data_in_g_d2 (.I(FE_OFN26_wr_data_in_g_d2),
	.Z(wr_data_in_g_d2));
   CKBD8BWP FE_OFC25_couple_en (.I(FE_OFN25_couple_en),
	.Z(couple_en));
   BUFFD4BWP FE_OFC24_rstn (.I(rstn),
	.Z(FE_OFN24_rstn));
   CKBD8BWP FE_OFC23_p_code_vld_bus_0 (.I(FE_OFN23_p_code_vld_bus_0),
	.Z(p_code_vld_bus[0]));
   CKBD8BWP FE_OFC22_p_code_vld_bus_1 (.I(FE_OFN22_p_code_vld_bus_1),
	.Z(p_code_vld_bus[1]));
   CKBD8BWP FE_OFC21_p_code_vld_bus_2 (.I(FE_OFN21_p_code_vld_bus_2),
	.Z(p_code_vld_bus[2]));
   CKBD8BWP FE_OFC20_p_code_vld_bus_3 (.I(FE_OFN20_p_code_vld_bus_3),
	.Z(p_code_vld_bus[3]));
   CKBD8BWP FE_OFC19_p_code_vld_bus_4 (.I(FE_OFN19_p_code_vld_bus_4),
	.Z(p_code_vld_bus[4]));
   CKBD8BWP FE_OFC18_p_code_vld_bus_5 (.I(FE_OFN18_p_code_vld_bus_5),
	.Z(p_code_vld_bus[5]));
   CKBD8BWP FE_OFC17_p_code_vld_bus_6 (.I(FE_OFN17_p_code_vld_bus_6),
	.Z(p_code_vld_bus[6]));
   CKBD8BWP FE_OFC16_p_code_vld_bus_7 (.I(FE_OFN16_p_code_vld_bus_7),
	.Z(p_code_vld_bus[7]));
   CKBD8BWP FE_OFC15_rd_rdy_bus_0 (.I(FE_OFN15_rd_rdy_bus_0),
	.Z(rd_rdy_bus[0]));
   CKBD8BWP FE_OFC14_rd_rdy_bus_1 (.I(FE_OFN14_rd_rdy_bus_1),
	.Z(rd_rdy_bus[1]));
   CKBD8BWP FE_OFC13_rd_rdy_bus_2 (.I(FE_OFN13_rd_rdy_bus_2),
	.Z(rd_rdy_bus[2]));
   CKBD8BWP FE_OFC12_rd_rdy_bus_3 (.I(FE_OFN12_rd_rdy_bus_3),
	.Z(rd_rdy_bus[3]));
   CKBD8BWP FE_OFC11_rd_rdy_bus_4 (.I(FE_OFN11_rd_rdy_bus_4),
	.Z(rd_rdy_bus[4]));
   CKBD8BWP FE_OFC10_rd_rdy_bus_5 (.I(FE_OFN10_rd_rdy_bus_5),
	.Z(rd_rdy_bus[5]));
   CKBD8BWP FE_OFC9_rd_rdy_bus_6 (.I(FE_OFN9_rd_rdy_bus_6),
	.Z(rd_rdy_bus[6]));
   CKBD8BWP FE_OFC8_rd_rdy_bus_7 (.I(FE_OFN8_rd_rdy_bus_7),
	.Z(rd_rdy_bus[7]));
   CKBD8BWP FE_OFC7_wr_vld_bus_0 (.I(FE_OFN7_wr_vld_bus_0),
	.Z(wr_vld_bus[0]));
   CKBD8BWP FE_OFC6_wr_vld_bus_1 (.I(FE_OFN6_wr_vld_bus_1),
	.Z(wr_vld_bus[1]));
   CKBD8BWP FE_OFC5_wr_vld_bus_2 (.I(FE_OFN5_wr_vld_bus_2),
	.Z(wr_vld_bus[2]));
   CKBD8BWP FE_OFC4_wr_vld_bus_3 (.I(FE_OFN4_wr_vld_bus_3),
	.Z(wr_vld_bus[3]));
   CKBD8BWP FE_OFC3_wr_vld_bus_4 (.I(FE_OFN3_wr_vld_bus_4),
	.Z(wr_vld_bus[4]));
   CKBD8BWP FE_OFC2_wr_vld_bus_5 (.I(FE_OFN2_wr_vld_bus_5),
	.Z(wr_vld_bus[5]));
   CKBD8BWP FE_OFC1_wr_vld_bus_6 (.I(FE_OFN1_wr_vld_bus_6),
	.Z(wr_vld_bus[6]));
   CKBD8BWP FE_OFC0_wr_vld_bus_7 (.I(FE_OFN0_wr_vld_bus_7),
	.Z(wr_vld_bus[7]));
   DFCNQD1BWP en_g_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(en_g),
	.Q(en_g_d1));
   DFCNQD1BWP wr_data_in_g_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(wr_data_in_g),
	.Q(wr_data_in_g_d1));
   DFCNQD1BWP p_en_d1_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(p_en),
	.Q(p_en_d1));
   DFCNQD1BWP p_en_d2_reg (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN54_p_en_d1),
	.Q(p_en_d2));
   DFCNQD1BWP col_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n72),
	.Q(col_id[0]));
   DFCNQD1BWP ul_cur_state_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n85),
	.Q(ul_cur_state[1]));
   DFCNQD1BWP ul_cur_state_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n86),
	.Q(ul_cur_state[0]));
   DFCNQD1BWP col_id_reg_1_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n73),
	.Q(col_id[1]));
   DFCNQD1BWP col_id_reg_2_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n74),
	.Q(col_id[2]));
   DFCNQD1BWP col_id_reg_3_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n75),
	.Q(col_id[3]));
   DFCNQD1BWP col_id_reg_4_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n76),
	.Q(col_id[4]));
   DFCNQD1BWP col_id_reg_5_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n77),
	.Q(col_id[5]));
   DFCNQD1BWP col_id_reg_6_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n78),
	.Q(col_id[6]));
   DFCNQD1BWP col_id_reg_7_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n79),
	.Q(col_id[7]));
   DFCNQD1BWP col_id_reg_8_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n800),
	.Q(col_id[8]));
   DFCNQD1BWP col_id_reg_9_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n810),
	.Q(col_id[9]));
   DFCNQD1BWP col_id_reg_10_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN65_n820),
	.Q(col_id[10]));
   DFCNQD1BWP row_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n89),
	.Q(row_id[0]));
   DFCNQD1BWP row_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n88),
	.Q(row_id[1]));
   DFCNQD1BWP row_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n87),
	.Q(row_id[2]));
   DFCNQD1BWP rd_row_id_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n900),
	.Q(rd_row_id[2]));
   DFCNQD1BWP rd_row_id_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n890),
	.Q(rd_row_id[1]));
   DFCNQD1BWP rd_row_id_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n880),
	.Q(FE_PHN38_rd_row_id_0));
   DFCNQD1BWP rd_row_id_d1_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN37_rd_row_id_2),
	.Q(rd_row_id_d1[2]));
   DFCNQD1BWP rd_row_id_d1_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN42_rd_row_id_1),
	.Q(rd_row_id_d1[1]));
   DFCNQD1BWP rd_row_id_d1_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(rd_row_id[0]),
	.Q(rd_row_id_d1[0]));
   DFCNQD1BWP phase_col_id_reg_0_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN62_n127),
	.Q(phase_col_id[0]));
   DFCNQD1BWP dl_cur_state_reg (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN61_dl_next_state),
	.Q(dl_cur_state));
   DFCNQD1BWP phase_col_id_reg_1_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN63_n1280),
	.Q(phase_col_id[1]));
   DFCNQD1BWP phase_col_id_reg_2_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN66_n129),
	.Q(phase_col_id[2]));
   DFCNQD1BWP phase_col_id_reg_3_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN64_n1300),
	.Q(phase_col_id[3]));
   DFCNQD1BWP phase_col_id_reg_4_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN67_n131),
	.Q(phase_col_id[4]));
   DFCNQD1BWP phase_col_id_reg_5_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1320),
	.Q(phase_col_id[5]));
   DFCNQD1BWP phase_col_id_reg_6_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN68_n133),
	.Q(phase_col_id[6]));
   DFCNQD1BWP phase_row_id_reg_0_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n83),
	.Q(phase_row_id[0]));
   DFCNQD1BWP phase_row_id_reg_1_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n82),
	.Q(phase_row_id[1]));
   DFCNQD1BWP phase_row_id_reg_2_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n81),
	.Q(phase_row_id[2]));
   DFCNQD1BWP dl_cur_state_d1_reg (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN57_dl_cur_state),
	.Q(dl_cur_state_d1));
   DFCNQD1BWP dl_cur_state_d2_reg (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN43_dl_cur_state_d1),
	.Q(dl_cur_state_d2));
   DFCNQD1BWP phase_row_id_d1_reg_2_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN34_phase_row_id_2),
	.Q(phase_row_id_d1[2]));
   DFCNQD1BWP phase_row_id_d2_reg_2_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN39_phase_row_id_d1_2),
	.Q(phase_row_id_d2[2]));
   DFCNQD1BWP phase_row_id_d1_reg_1_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN45_phase_row_id_1),
	.Q(phase_row_id_d1[1]));
   DFCNQD1BWP phase_row_id_d2_reg_1_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN41_phase_row_id_d1_1),
	.Q(phase_row_id_d2[1]));
   DFCNQD1BWP phase_row_id_d1_reg_0_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN51_phase_row_id_0),
	.Q(phase_row_id_d1[0]));
   DFCNQD1BWP phase_row_id_d2_reg_0_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_PHN35_phase_row_id_d1_0),
	.Q(phase_row_id_d2[0]));
   DFCNQD1BWP ul_cur_state_d1_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n80),
	.Q(ul_cur_state_d1_0_));
   DFCNQD1BWP wr_data_in_g_d2_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(FE_PHN36_wr_data_in_g_d1),
	.Q(FE_OFN26_wr_data_in_g_d2));
   DFCNQD1BWP rd_data_out_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n960),
	.Q(FE_OFN28_rd_data_out_g));
   DFCNQD1BWP rd_vld_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n93),
	.Q(FE_OFN27_rd_vld_g));
   DFCNQD1BWP p_code_vld_bus_reg_7_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n141),
	.Q(FE_OFN16_p_code_vld_bus_7));
   DFCNQD1BWP p_code_vld_bus_reg_6_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1400),
	.Q(FE_OFN17_p_code_vld_bus_6));
   DFCNQD1BWP p_code_vld_bus_reg_5_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n139),
	.Q(FE_OFN18_p_code_vld_bus_5));
   DFCNQD1BWP p_code_vld_bus_reg_4_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1380),
	.Q(FE_OFN19_p_code_vld_bus_4));
   DFCNQD1BWP p_code_vld_bus_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n137),
	.Q(FE_OFN20_p_code_vld_bus_3));
   DFCNQD1BWP p_code_vld_bus_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1360),
	.Q(FE_OFN21_p_code_vld_bus_2));
   DFCNQD1BWP p_code_vld_bus_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n135),
	.Q(FE_OFN22_p_code_vld_bus_1));
   DFCNQD1BWP p_code_vld_bus_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1340),
	.Q(FE_OFN23_p_code_vld_bus_0));
   DFCNQD1BWP p_out_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n1460),
	.Q(FE_OFN30_p_out_g));
   DFCNQD1BWP p_out_vld_g_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n1440),
	.Q(FE_OFN29_p_out_vld_g));
   DFCNQD1BWP wr_vld_bus_reg_7_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_OFN32_n1610),
	.Q(FE_OFN0_wr_vld_bus_7));
   DFCNQD1BWP wr_vld_bus_reg_6_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(FE_OFN31_n1590),
	.Q(FE_OFN1_wr_vld_bus_6));
   DFCNQD1BWP wr_vld_bus_reg_5_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1570),
	.Q(FE_OFN2_wr_vld_bus_5));
   DFCNQD1BWP wr_vld_bus_reg_4_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1550),
	.Q(FE_OFN3_wr_vld_bus_4));
   DFCNQD1BWP wr_vld_bus_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1530),
	.Q(FE_OFN4_wr_vld_bus_3));
   DFCNQD1BWP wr_vld_bus_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1510),
	.Q(FE_OFN5_wr_vld_bus_2));
   DFCNQD1BWP wr_vld_bus_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n149),
	.Q(FE_OFN6_wr_vld_bus_1));
   DFCNQD1BWP wr_vld_bus_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n147),
	.Q(FE_OFN7_wr_vld_bus_0));
   DFCNQD1BWP rd_rdy_bus_reg_7_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1620),
	.Q(FE_OFN8_rd_rdy_bus_7));
   DFCNQD1BWP rd_rdy_bus_reg_6_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1600),
	.Q(FE_OFN9_rd_rdy_bus_6));
   DFCNQD1BWP rd_rdy_bus_reg_5_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1580),
	.Q(FE_OFN10_rd_rdy_bus_5));
   DFCNQD1BWP rd_rdy_bus_reg_4_ (.CDN(FE_OFN24_rstn),
	.CP(CTS_1),
	.D(n1560),
	.Q(FE_OFN11_rd_rdy_bus_4));
   DFCNQD1BWP rd_rdy_bus_reg_3_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1540),
	.Q(FE_OFN12_rd_rdy_bus_3));
   DFCNQD1BWP rd_rdy_bus_reg_2_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1520),
	.Q(FE_OFN13_rd_rdy_bus_2));
   DFCNQD1BWP rd_rdy_bus_reg_1_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1500),
	.Q(FE_OFN14_rd_rdy_bus_1));
   DFCNQD1BWP rd_rdy_bus_reg_0_ (.CDN(rstn),
	.CP(CTS_1),
	.D(n1480),
	.Q(FE_OFN15_rd_rdy_bus_0));
   DFCNQD1BWP couple_en_reg (.CDN(rstn),
	.CP(CTS_1),
	.D(n84),
	.Q(FE_OFN25_couple_en));
   IND2D0BWP U142 (.A1(FE_PHN46_FE_OFN25_couple_en),
	.B1(n253),
	.ZN(n84));
   INVD0BWP U203 (.I(col_id[5]),
	.ZN(n187));
   TIEHBWP U204 (.Z(n80));
   CKND2D0BWP U205 (.A1(phase_row_id[0]),
	.A2(dl_cur_state),
	.ZN(n153));
   INVD0BWP U206 (.I(phase_row_id[1]),
	.ZN(n257));
   NR3D1BWP U207 (.A1(n153),
	.A2(phase_row_id[2]),
	.A3(n257),
	.ZN(n137));
   INVD0BWP U208 (.I(FE_PHN51_phase_row_id_0),
	.ZN(n176));
   INVD0BWP U209 (.I(phase_col_id[0]),
	.ZN(n160));
   NR4D0BWP U210 (.A1(phase_col_id[1]),
	.A2(phase_col_id[2]),
	.A3(phase_col_id[5]),
	.A4(n160),
	.ZN(n150));
   ND4D1BWP U211 (.A1(phase_col_id[4]),
	.A2(phase_col_id[3]),
	.A3(phase_col_id[6]),
	.A4(n150),
	.ZN(n151));
   CKND2D0BWP U212 (.A1(phase_row_id[2]),
	.A2(phase_row_id[1]),
	.ZN(n152));
   OAI31D0BWP U213 (.A1(n176),
	.A2(n151),
	.A3(n152),
	.B(FE_PHN57_dl_cur_state),
	.ZN(n164));
   INVD0BWP U214 (.I(phase_row_id[2]),
	.ZN(n154));
   CKND2D0BWP U215 (.A1(dl_cur_state),
	.A2(n151),
	.ZN(n169));
   MOAI22D0BWP U216 (.A1(n164),
	.A2(n154),
	.B1(n137),
	.B2(n169),
	.ZN(n81));
   CKND2D1BWP U217 (.A1(ul_cur_state[0]),
	.A2(ul_cur_state[1]),
	.ZN(n253));
   INVD0BWP U218 (.I(row_id[2]),
	.ZN(n200));
   NR2XD0BWP U219 (.A1(n253),
	.A2(n200),
	.ZN(n900));
   INVD0BWP U220 (.I(FE_PHN57_dl_cur_state),
	.ZN(n163));
   NR2D0BWP U221 (.A1(n163),
	.A2(phase_col_id[0]),
	.ZN(n127));
   CKND1BWP U222 (.I(ul_cur_state[0]),
	.ZN(n194));
   NR2D0BWP U223 (.A1(n194),
	.A2(FE_PHN52_col_id_0),
	.ZN(n72));
   NR2XD0BWP U224 (.A1(n152),
	.A2(n153),
	.ZN(n141));
   NR2D0BWP U225 (.A1(n163),
	.A2(phase_row_id[0]),
	.ZN(n175));
   INVD0BWP U226 (.I(n175),
	.ZN(n258));
   NR2D0BWP U227 (.A1(n152),
	.A2(n258),
	.ZN(n1400));
   OR2D0BWP U228 (.A1(n153),
	.A2(phase_row_id[1]),
	.Z(n179));
   NR2XD1BWP U229 (.A1(n179),
	.A2(phase_row_id[2]),
	.ZN(n135));
   NR2D0BWP U230 (.A1(n154),
	.A2(n179),
	.ZN(n139));
   CKND2D0BWP U231 (.A1(n175),
	.A2(n257),
	.ZN(n155));
   NR2D2BWP U232 (.A1(n155),
	.A2(phase_row_id[2]),
	.ZN(n1340));
   NR2D0BWP U233 (.A1(n155),
	.A2(n154),
	.ZN(n1380));
   NR2D0BWP U234 (.A1(n194),
	.A2(ul_cur_state[1]),
	.ZN(n157));
   CKND2D0BWP U235 (.A1(n157),
	.A2(n200),
	.ZN(n254));
   CKND2D1BWP U236 (.A1(row_id[1]),
	.A2(row_id[0]),
	.ZN(n201));
   NR2D0BWP U237 (.A1(n254),
	.A2(n201),
	.ZN(n1530));
   INVD0BWP U238 (.I(row_id[0]),
	.ZN(n190));
   INVD0BWP U239 (.I(row_id[1]),
	.ZN(n256));
   CKND2D1BWP U240 (.A1(n190),
	.A2(n256),
	.ZN(n252));
   NR2D0BWP U241 (.A1(n254),
	.A2(n252),
	.ZN(n147));
   CKND2D1BWP U242 (.A1(row_id[0]),
	.A2(n256),
	.ZN(n192));
   NR2D0BWP U243 (.A1(n254),
	.A2(n192),
	.ZN(n149));
   INVD0BWP U244 (.I(n900),
	.ZN(n156));
   NR2XD0BWP U245 (.A1(n156),
	.A2(n192),
	.ZN(n1580));
   NR2D0BWP U246 (.A1(n156),
	.A2(n252),
	.ZN(n1560));
   CKND2D1BWP U247 (.A1(row_id[2]),
	.A2(n157),
	.ZN(n255));
   NR2D0BWP U248 (.A1(n255),
	.A2(n201),
	.ZN(n1610));
   NR2D0BWP U249 (.A1(n255),
	.A2(n252),
	.ZN(n1550));
   NR2D0BWP U250 (.A1(n255),
	.A2(n192),
	.ZN(n1570));
   NR2D0BWP U251 (.A1(n253),
	.A2(n190),
	.ZN(n880));
   AN3D0BWP U252 (.A1(n880),
	.A2(n256),
	.A3(n200),
	.Z(n1500));
   NR2D0BWP U253 (.A1(n253),
	.A2(n256),
	.ZN(n890));
   CKND2D0BWP U254 (.A1(n890),
	.A2(n200),
	.ZN(n158));
   NR2D0BWP U255 (.A1(n158),
	.A2(n190),
	.ZN(n1540));
   NR2D0BWP U256 (.A1(n158),
	.A2(FE_PHN33_row_id_0),
	.ZN(n1520));
   CKND2D0BWP U257 (.A1(row_id[2]),
	.A2(n890),
	.ZN(n159));
   NR2D2BWP U258 (.A1(n159),
	.A2(FE_PHN33_row_id_0),
	.ZN(n1600));
   NR2D2BWP U259 (.A1(n159),
	.A2(n190),
	.ZN(n1620));
   INVD0BWP U260 (.I(phase_col_id[1]),
	.ZN(n161));
   NR2D0BWP U261 (.A1(n160),
	.A2(n161),
	.ZN(n168));
   AOI211D0BWP U262 (.A1(n161),
	.A2(n160),
	.B(n168),
	.C(n169),
	.ZN(n1280));
   INVD0BWP U263 (.I(phase_col_id[3]),
	.ZN(n162));
   CKND2D0BWP U264 (.A1(phase_col_id[2]),
	.A2(n168),
	.ZN(n167));
   NR2D0BWP U265 (.A1(n167),
	.A2(n162),
	.ZN(n166));
   AOI211D0BWP U266 (.A1(n162),
	.A2(n167),
	.B(n166),
	.C(n169),
	.ZN(n1300));
   CKND2D0BWP U267 (.A1(p_en_d2),
	.A2(n163),
	.ZN(n165));
   OAI21D0BWP U268 (.A1(p_en_d1),
	.A2(n165),
	.B(n164),
	.ZN(dl_next_state));
   INVD0BWP U269 (.I(n169),
	.ZN(n197));
   CKND2D0BWP U270 (.A1(phase_col_id[4]),
	.A2(n166),
	.ZN(n170));
   OA211D0BWP U271 (.A1(phase_col_id[4]),
	.A2(n166),
	.B(n197),
	.C(n170),
	.Z(n131));
   OA211D0BWP U272 (.A1(phase_col_id[2]),
	.A2(n168),
	.B(n197),
	.C(n167),
	.Z(n129));
   INVD0BWP U273 (.I(phase_col_id[5]),
	.ZN(n171));
   NR2D0BWP U274 (.A1(n170),
	.A2(n171),
	.ZN(n199));
   AOI211D0BWP U275 (.A1(n171),
	.A2(n170),
	.B(n199),
	.C(n169),
	.ZN(FE_PHN70_n1320));
   INVD0BWP U276 (.I(col_id[0]),
	.ZN(n181));
   INVD0BWP U277 (.I(col_id[1]),
	.ZN(n182));
   NR2D0BWP U278 (.A1(n181),
	.A2(n182),
	.ZN(n180));
   NR4D0BWP U279 (.A1(col_id[2]),
	.A2(col_id[4]),
	.A3(col_id[7]),
	.A4(n181),
	.ZN(n174));
   NR2D0BWP U280 (.A1(col_id[3]),
	.A2(col_id[1]),
	.ZN(n172));
   AN4D0BWP U281 (.A1(col_id[5]),
	.A2(col_id[6]),
	.A3(col_id[9]),
	.A4(n172),
	.Z(n173));
   AN4D2BWP U282 (.A1(col_id[8]),
	.A2(col_id[10]),
	.A3(n174),
	.A4(n173),
	.Z(n191));
   NR2D3BWP U283 (.A1(n194),
	.A2(n191),
	.ZN(n209));
   CKND2D0BWP U284 (.A1(FE_PHN60_col_id_2),
	.A2(n180),
	.ZN(n184));
   OA211D0BWP U285 (.A1(FE_PHN60_col_id_2),
	.A2(n180),
	.B(n209),
	.C(n184),
	.Z(n74));
   INVD0BWP U286 (.I(col_id[3]),
	.ZN(n185));
   NR2D0BWP U287 (.A1(n184),
	.A2(n185),
	.ZN(n183));
   CKND2D0BWP U288 (.A1(FE_PHN59_col_id_4),
	.A2(n183),
	.ZN(n186));
   OA211D0BWP U289 (.A1(FE_PHN59_col_id_4),
	.A2(n183),
	.B(n209),
	.C(n186),
	.Z(n76));
   NR2D0BWP U290 (.A1(n197),
	.A2(n175),
	.ZN(n178));
   AOI21D0BWP U291 (.A1(n197),
	.A2(n176),
	.B(n178),
	.ZN(n83));
   INVD0BWP U292 (.I(FE_PHN40_ul_cur_state_1),
	.ZN(n188));
   OAI21D0BWP U293 (.A1(ul_cur_state[0]),
	.A2(en_g_d1),
	.B(n188),
	.ZN(n177));
   IND3D0BWP U294 (.A1(n201),
	.B1(n191),
	.B2(FE_PHN55_row_id_2),
	.ZN(n189));
   CKND2D0BWP U295 (.A1(ul_cur_state[0]),
	.A2(n189),
	.ZN(n202));
   CKND2D0BWP U296 (.A1(FE_PHN69_n177),
	.A2(n202),
	.ZN(n86));
   OAI22D0BWP U297 (.A1(n197),
	.A2(n179),
	.B1(n178),
	.B2(n257),
	.ZN(n82));
   INVD0BWP U298 (.I(n209),
	.ZN(n206));
   AOI211D0BWP U299 (.A1(FE_PHN49_n182),
	.A2(n181),
	.B(n180),
	.C(n206),
	.ZN(n73));
   AOI211D0BWP U300 (.A1(FE_PHN47_n185),
	.A2(n184),
	.B(n183),
	.C(n206),
	.ZN(n75));
   NR2D0BWP U301 (.A1(n186),
	.A2(n187),
	.ZN(n196));
   AOI211D0BWP U302 (.A1(FE_PHN48_n187),
	.A2(n186),
	.B(n196),
	.C(n206),
	.ZN(n77));
   AOI21D0BWP U303 (.A1(n189),
	.A2(n188),
	.B(n194),
	.ZN(n85));
   AOI21D0BWP U304 (.A1(ul_cur_state[0]),
	.A2(n190),
	.B(n209),
	.ZN(n195));
   AOI21D0BWP U305 (.A1(n209),
	.A2(n190),
	.B(n195),
	.ZN(n89));
   IND2D0BWP U306 (.A1(n192),
	.B1(n191),
	.ZN(n193));
   OAI22D0BWP U307 (.A1(n195),
	.A2(n256),
	.B1(n194),
	.B2(n193),
	.ZN(n88));
   CKND2D0BWP U308 (.A1(FE_PHN56_col_id_6),
	.A2(n196),
	.ZN(n203));
   OA211D0BWP U309 (.A1(FE_PHN71_col_id_6),
	.A2(n196),
	.B(n209),
	.C(n203),
	.Z(n78));
   OAI21D0BWP U310 (.A1(phase_col_id[6]),
	.A2(n199),
	.B(n197),
	.ZN(n198));
   AOI21D0BWP U311 (.A1(phase_col_id[6]),
	.A2(n199),
	.B(n198),
	.ZN(n133));
   OAI32D0BWP U312 (.A1(n202),
	.A2(n209),
	.A3(n201),
	.B1(n200),
	.B2(n202),
	.ZN(n87));
   INVD0BWP U313 (.I(col_id[7]),
	.ZN(n204));
   NR2D0BWP U314 (.A1(n203),
	.A2(n204),
	.ZN(n205));
   AOI211D0BWP U315 (.A1(FE_PHN44_n204),
	.A2(n203),
	.B(n205),
	.C(n206),
	.ZN(n79));
   CKND2D0BWP U316 (.A1(FE_PHN53_col_id_8),
	.A2(n205),
	.ZN(n207));
   OA211D0BWP U317 (.A1(FE_PHN53_col_id_8),
	.A2(n205),
	.B(n209),
	.C(n207),
	.Z(n800));
   INVD0BWP U318 (.I(col_id[9]),
	.ZN(n208));
   NR2D0BWP U319 (.A1(n207),
	.A2(n208),
	.ZN(n211));
   AOI211D0BWP U320 (.A1(FE_PHN50_n208),
	.A2(n207),
	.B(n211),
	.C(n206),
	.ZN(n810));
   OAI21D0BWP U321 (.A1(col_id[10]),
	.A2(n211),
	.B(n209),
	.ZN(n210));
   AOI21D0BWP U322 (.A1(col_id[10]),
	.A2(n211),
	.B(n210),
	.ZN(n820));
   INVD0BWP U323 (.I(rd_row_id_d1[1]),
	.ZN(n213));
   NR2D0BWP U324 (.A1(n213),
	.A2(rd_row_id_d1[2]),
	.ZN(n221));
   AOI21D0BWP U325 (.A1(n221),
	.A2(rd_data_out_bus[2]),
	.B(rd_row_id_d1[0]),
	.ZN(n220));
   NR2D0BWP U326 (.A1(rd_row_id_d1[2]),
	.A2(rd_row_id_d1[1]),
	.ZN(n223));
   INVD0BWP U327 (.I(rd_row_id_d1[2]),
	.ZN(n212));
   NR2D0BWP U328 (.A1(n212),
	.A2(rd_row_id_d1[1]),
	.ZN(n222));
   AOI22D0BWP U329 (.A1(n223),
	.A2(rd_data_out_bus[0]),
	.B1(n222),
	.B2(rd_data_out_bus[4]),
	.ZN(n219));
   NR2D0BWP U330 (.A1(n213),
	.A2(n212),
	.ZN(n227));
   CKND2D0BWP U331 (.A1(n227),
	.A2(rd_data_out_bus[6]),
	.ZN(n218));
   CKND2D0BWP U332 (.A1(n221),
	.A2(rd_data_out_bus[3]),
	.ZN(n215));
   AOI22D0BWP U333 (.A1(n223),
	.A2(rd_data_out_bus[1]),
	.B1(n222),
	.B2(rd_data_out_bus[5]),
	.ZN(n214));
   ND3D0BWP U334 (.A1(n215),
	.A2(n214),
	.A3(rd_row_id_d1[0]),
	.ZN(n216));
   AOI32D0BWP U335 (.A1(n227),
	.A2(ul_cur_state_d1_0_),
	.A3(rd_data_out_bus[7]),
	.B1(n216),
	.B2(ul_cur_state_d1_0_),
	.ZN(n217));
   AOI31D1BWP U336 (.A1(n220),
	.A2(n219),
	.A3(n218),
	.B(n217),
	.ZN(n960));
   AOI21D0BWP U337 (.A1(n221),
	.A2(rd_vld_bus[2]),
	.B(rd_row_id_d1[0]),
	.ZN(n231));
   AOI22D0BWP U338 (.A1(n223),
	.A2(rd_vld_bus[0]),
	.B1(n222),
	.B2(rd_vld_bus[4]),
	.ZN(n230));
   CKND2D0BWP U339 (.A1(n227),
	.A2(rd_vld_bus[6]),
	.ZN(n229));
   CKND2D0BWP U340 (.A1(n221),
	.A2(rd_vld_bus[3]),
	.ZN(n225));
   AOI22D0BWP U341 (.A1(n223),
	.A2(rd_vld_bus[1]),
	.B1(n222),
	.B2(rd_vld_bus[5]),
	.ZN(n224));
   ND3D0BWP U342 (.A1(n225),
	.A2(n224),
	.A3(rd_row_id_d1[0]),
	.ZN(n226));
   AOI32D0BWP U343 (.A1(n227),
	.A2(ul_cur_state_d1_0_),
	.A3(rd_vld_bus[7]),
	.B1(n226),
	.B2(ul_cur_state_d1_0_),
	.ZN(n228));
   AOI31D2BWP U344 (.A1(n231),
	.A2(n230),
	.A3(n229),
	.B(n228),
	.ZN(FE_PHN58_n93));
   INVD0BWP U345 (.I(phase_row_id_d2[1]),
	.ZN(n233));
   NR2D0BWP U346 (.A1(n233),
	.A2(phase_row_id_d2[2]),
	.ZN(n241));
   AOI21D0BWP U347 (.A1(n241),
	.A2(p_out_vld_bus[2]),
	.B(phase_row_id_d2[0]),
	.ZN(n240));
   NR2D0BWP U348 (.A1(phase_row_id_d2[2]),
	.A2(phase_row_id_d2[1]),
	.ZN(n243));
   INVD0BWP U349 (.I(phase_row_id_d2[2]),
	.ZN(n232));
   NR2D0BWP U350 (.A1(n232),
	.A2(phase_row_id_d2[1]),
	.ZN(n242));
   AOI22D0BWP U351 (.A1(n243),
	.A2(p_out_vld_bus[0]),
	.B1(n242),
	.B2(p_out_vld_bus[4]),
	.ZN(n239));
   NR2D0BWP U352 (.A1(n233),
	.A2(n232),
	.ZN(n247));
   CKND2D0BWP U353 (.A1(n247),
	.A2(p_out_vld_bus[6]),
	.ZN(n238));
   CKND2D0BWP U354 (.A1(n241),
	.A2(p_out_vld_bus[3]),
	.ZN(n235));
   AOI22D0BWP U355 (.A1(n243),
	.A2(p_out_vld_bus[1]),
	.B1(n242),
	.B2(p_out_vld_bus[5]),
	.ZN(n234));
   ND3D0BWP U356 (.A1(n235),
	.A2(n234),
	.A3(phase_row_id_d2[0]),
	.ZN(n236));
   AOI32D0BWP U357 (.A1(n247),
	.A2(dl_cur_state_d2),
	.A3(p_out_vld_bus[7]),
	.B1(n236),
	.B2(dl_cur_state_d2),
	.ZN(n237));
   AOI31D2BWP U358 (.A1(n240),
	.A2(n239),
	.A3(n238),
	.B(n237),
	.ZN(n1440));
   AOI21D0BWP U359 (.A1(n241),
	.A2(p_out_bus[2]),
	.B(phase_row_id_d2[0]),
	.ZN(n251));
   AOI22D0BWP U360 (.A1(n243),
	.A2(p_out_bus[0]),
	.B1(n242),
	.B2(p_out_bus[4]),
	.ZN(n250));
   CKND2D0BWP U361 (.A1(n247),
	.A2(p_out_bus[6]),
	.ZN(n249));
   CKND2D0BWP U362 (.A1(n241),
	.A2(p_out_bus[3]),
	.ZN(n245));
   AOI22D0BWP U363 (.A1(n243),
	.A2(p_out_bus[1]),
	.B1(n242),
	.B2(p_out_bus[5]),
	.ZN(n244));
   ND3D0BWP U364 (.A1(n245),
	.A2(n244),
	.A3(phase_row_id_d2[0]),
	.ZN(n246));
   AOI32D0BWP U365 (.A1(n247),
	.A2(dl_cur_state_d2),
	.A3(p_out_bus[7]),
	.B1(n246),
	.B2(dl_cur_state_d2),
	.ZN(n248));
   AOI31D2BWP U366 (.A1(n251),
	.A2(n250),
	.A3(n249),
	.B(n248),
	.ZN(n1460));
   NR3D0BWP U367 (.A1(FE_PHN55_row_id_2),
	.A2(n253),
	.A3(n252),
	.ZN(n1480));
   NR3D0BWP U368 (.A1(FE_PHN33_row_id_0),
	.A2(n256),
	.A3(n254),
	.ZN(n1510));
   NR3D0BWP U369 (.A1(row_id[0]),
	.A2(n256),
	.A3(n255),
	.ZN(n1590));
   NR3D1BWP U370 (.A1(phase_row_id[2]),
	.A2(n258),
	.A3(n257),
	.ZN(n1360));
endmodule

