(globals
	version = 3

	io_order = clockwise
)

(row_margin
	(top
		(io_row ring_number=1 margin=0.0000)
	)
	(left
        (io_row ring_number=1 margin=0.0000)
        )
	(bottom
        (io_row ring_number=1 margin=0.0000)
        )
	(right
        (io_row ring_number=1 margin=0.0000)
        )
)
(iopad
	(topright
	(locals ring_number=1)
	(inst name="CORNER_TR1" cell=PCORNERA orientation=R180)
	)
	(topleft
        (locals ring_number=1)
        (inst name="CORNER_TL1" cell=PCORNERA orientation=R270)
        )
	(bottomright
        (locals ring_number=1)
        (inst name="CORNER_BR1" cell=PCORNERA orientation=R90)
        )
	(bottomleft
        (locals ring_number=1)
        (inst name="CORNER_BL1" cell=PCORNER orientation=R0)
        )

	#  bottom to top
	(left
		(locals ring_number=1)
		(inst name='io_tst_us_sel_2_2' cell=PDDDGZ place_status=placed offset=215)
		(inst name='io_tst_us_sel_2_1' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_2_0' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_1_3' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_1_2' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_1_1' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_1_0' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_0_3' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_0_2' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_0_1' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_us_sel_0_0' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_POC' cell=PVDD2POC place_status=placed space=30)
		(inst name='io_HVDD0' cell=PVDD1DGZ place_status=placed space=30)
		(inst name='io_HVSS0' cell=PVSS1DGZ place_status=placed space=30)
		(inst name='io_HDVDD0' cell=PVDD2DGZ place_status=placed space=30)
		(inst name='io_HDVSS0' cell=PVSS2DGZ place_status=placed space=30)
		(inst name='io_tst_clk' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_en_g' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_wr_data_in_g' cell=PDD24CDG place_status=placed space=30)
		(inst name='io_tst_couple_en' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_tst_rd_vld_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_tst_rd_data_out_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_tst_p_out_vld_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_tst_p_out_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_tst_p_en' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_HVDD1' cell=PVDD1DGZ place_status=placed space=30)
		(inst name='io_HVSS1' cell=PVSS1DGZ place_status=placed space=30)
		(inst name='io_HDVDD1' cell=PVDD2DGZ place_status=placed space=30)
		(inst name='io_HDVSS1' cell=PVSS2DGZ place_status=placed space=30)
		(inst name='io_rstn' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_clk' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_en_g' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_wr_data_in_g' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_rd_data_out_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_rd_vld_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_p_out_vld_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_p_out_g' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_couple_en' cell=PDO24CDG place_status=placed space=30)
		(inst name='io_p_en' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_b2_ctrl_0' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_b2_ctrl_1' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_b2_ctrl_2' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_b2_ctrl_3' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_b2_ctrl_4' cell=PDDDGZ place_status=placed space=30)
		(inst name='io_tst_b2_ctrl_5' cell=PDDDGZ place_status=placed space=30)
		(inst name='break0' cell=PRCUTA place_status=placed space=40)
		(inst name='io_HS_AVSS0' cell=PVSS3A place_status=placed space=0)
	)

	# left to right
	(top
		(inst name='io_HS_AVDD0' cell=PVDD3A place_status=placed offset=195)
		(inst name='io_HS_VSS0' cell=PVSS3AC place_status=placed space=120)
		(inst name='io_HS_VDD0' cell=PVDD3AC place_status=placed space=0)
	)

	# left to right
	(right
		(inst name='io_HS_AVDD2' cell=PVDD3A place_status=placed offset=195) 
		(inst name='io_HS_AVSS2' cell=PVSS3A place_status=placed space=0) 
		(inst name='break2' cell=PRCUTA place_status=placed space=30)
		(inst name='io_tst_sabil_bk' cell=PDB3AC place_status=placed space=60)
		(inst name='io_tst_us_ro_2' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_us_ro_1' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_us_ro_0' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_osc_vb' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_b2_cvb1' cell=PDB3AC place_status=placed space=0)
		(inst name='io_VDD2' cell=PVDD3AC place_status=placed space=0)
		(inst name='io_VSS2' cell=PVSS3AC place_status=placed space=0)
		(inst name='io_tst_b2_cvb2' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_b3_cvb' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_p_mod' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_cp_sel' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_p_ota_vb' cell=PDB3AC place_status=placed space=0)
		(inst name='io_VDD1' cell=PVDD3AC place_status=placed space=0)
		(inst name='io_VSS1' cell=PVSS3AC place_status=placed space=0)
		(inst name='io_osc_vb' cell=PDB3AC place_status=placed space=0)
		(inst name='io_b2_cvb1' cell=PDB3AC place_status=placed space=0)
		(inst name='io_b2_cvb2' cell=PDB3AC place_status=placed space=0)
		(inst name='io_cp_sel' cell=PDB3AC place_status=placed space=0)
		(inst name='io_HS_VDD1' cell=PVDD3AC place_status=placed space=0) 
		(inst name='io_HS_VSS1' cell=PVSS3AC place_status=placed space=0)
		(inst name='io_HS_AVDD1' cell=PVDD3A place_status=placed space=60)
		(inst name='io_HS_AVSS1' cell=PVSS3A place_status=placed space=0)
		(inst name='break1' cell=PRCUTA place_status=placed space=30)
		(inst name='io_sabil_bk' cell=PDB3AC place_status=placed space=0)
		(inst name='io_b3_cvb' cell=PDB3AC place_status=placed space=0)
		(inst name='io_p_ota_vb' cell=PDB3AC place_status=placed space=0)
		(inst name='io_p_mod' cell=PDB3AC place_status=placed space=0)
		(inst name='io_VDD0' cell=PVDD3AC place_status=placed space=0)
		(inst name='io_VSS0' cell=PVSS3AC place_status=placed space=0)
		(inst name='io_tst_b3_f_4' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_b3_f_3' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_b3_f_2' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_b3_f_1' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_b3_f_0' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_ro_tst' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_zq_ro_3' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_zq_ro_2' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_zq_ro_1' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_je_ro_2' cell=PDB3AC place_status=placed space=0)
		(inst name='io_tst_je_ro_1' cell=PDB3AC place_status=placed space=0)
	)

	# bottom to top
	(bottom
		(inst name='io_tst_us_sel_2_3' cell=PDDDGZ place_status=placed offset=205)
		(inst name='break3' cell=PRCUTA place_status=placed space=40)
		(inst name='io_HS_VDD2' cell=PVDD3AC place_status=placed space=0)
		(inst name='io_HS_VSS2' cell=PVSS3AC place_status=placed space=0)

	)
)

