/*
###############################################################
#  Generated by:      Cadence Innovus 19.12-s087_1
#  OS:                Linux x86_64(Host ID pdk5)
#  Generated on:      Tue Apr 28 12:35:00 2026
#  Design:            padframe
#  Command:           saveNetlist -phys ./output/padframe/padframe_digital_enc_all.v
###############################################################
*/
module PDDDGZ (
	PAD, 
	C);
   input PAD;
   output C;
endmodule

module PDO24CDG (
	I, 
	PAD);
   input I;
   output PAD;
endmodule

module PDB3AC (
	AIO);
   inout AIO;
endmodule

/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : S-2021.06-SP1
// Date      : Tue Apr 28 12:33:53 2026
/////////////////////////////////////////////////////////////
module padframe (
	pad_tst_us_sel_2, 
	pad_tst_us_sel_1, 
	pad_tst_us_sel_0, 
	pad_tst_clk, 
	pad_tst_en_g, 
	pad_tst_wr_data_in_g, 
	pad_tst_p_en, 
	pad_rstn, 
	pad_clk, 
	pad_en_g, 
	pad_wr_data_in_g, 
	pad_p_en, 
	pad_tst_b2_ctrl, 
	tst_couple_en, 
	tst_rd_vld_g, 
	tst_rd_data_out_g, 
	tst_p_out_vld_g, 
	tst_p_out_g, 
	rd_data_out_g, 
	rd_vld_g, 
	p_out_vld_g, 
	p_out_g, 
	couple_en, 
	tst_us_sel_2, 
	tst_us_sel_1, 
	tst_us_sel_0, 
	tst_clk, 
	tst_en_g, 
	tst_wr_data_in_g, 
	tst_p_en, 
	rstn, 
	clk, 
	en_g, 
	wr_data_in_g, 
	p_en, 
	tst_b2_ctrl, 
	pad_tst_couple_en, 
	pad_tst_rd_vld_g, 
	pad_tst_rd_data_out_g, 
	pad_tst_p_out_vld_g, 
	pad_tst_p_out_g, 
	pad_rd_data_out_g, 
	pad_rd_vld_g, 
	pad_p_out_vld_g, 
	pad_p_out_g, 
	pad_couple_en, 
	tst_je_ro_1, 
	tst_je_ro_2, 
	tst_zq_ro_1, 
	tst_zq_ro_2, 
	tst_zq_ro_3, 
	tst_ro_tst, 
	tst_b3_f, 
	p_mod, 
	p_ota_vb, 
	b3_cvb, 
	cp_sel, 
	b2_cvb2, 
	b2_cvb1, 
	osc_vb, 
	tst_p_ota_vb, 
	tst_cp_sel, 
	tst_p_mod, 
	tst_b3_cvb, 
	tst_b2_cvb2, 
	tst_b2_cvb1, 
	tst_osc_vb, 
	tst_us_ro_0, 
	tst_us_ro_1, 
	tst_us_ro_2, 
	tst_sabil_bk, 
	sabil_bk);
   input [3:0] pad_tst_us_sel_2;
   input [3:0] pad_tst_us_sel_1;
   input [3:0] pad_tst_us_sel_0;
   input pad_tst_clk;
   input pad_tst_en_g;
   input pad_tst_wr_data_in_g;
   input pad_tst_p_en;
   input pad_rstn;
   input pad_clk;
   input pad_en_g;
   input pad_wr_data_in_g;
   input pad_p_en;
   input [5:0] pad_tst_b2_ctrl;
   input tst_couple_en;
   input tst_rd_vld_g;
   input tst_rd_data_out_g;
   input tst_p_out_vld_g;
   input tst_p_out_g;
   input rd_data_out_g;
   input rd_vld_g;
   input p_out_vld_g;
   input p_out_g;
   input couple_en;
   output [3:0] tst_us_sel_2;
   output [3:0] tst_us_sel_1;
   output [3:0] tst_us_sel_0;
   output tst_clk;
   output tst_en_g;
   output tst_wr_data_in_g;
   output tst_p_en;
   output rstn;
   output clk;
   output en_g;
   output wr_data_in_g;
   output p_en;
   output [5:0] tst_b2_ctrl;
   output pad_tst_couple_en;
   output pad_tst_rd_vld_g;
   output pad_tst_rd_data_out_g;
   output pad_tst_p_out_vld_g;
   output pad_tst_p_out_g;
   output pad_rd_data_out_g;
   output pad_rd_vld_g;
   output pad_p_out_vld_g;
   output pad_p_out_g;
   output pad_couple_en;
   inout tst_je_ro_1;
   inout tst_je_ro_2;
   inout tst_zq_ro_1;
   inout tst_zq_ro_2;
   inout tst_zq_ro_3;
   inout tst_ro_tst;
   inout [4:0] tst_b3_f;
   inout p_mod;
   inout p_ota_vb;
   inout b3_cvb;
   inout cp_sel;
   inout b2_cvb2;
   inout b2_cvb1;
   inout osc_vb;
   inout tst_p_ota_vb;
   inout tst_cp_sel;
   inout tst_p_mod;
   inout tst_b3_cvb;
   inout tst_b2_cvb2;
   inout tst_b2_cvb1;
   inout tst_osc_vb;
   inout tst_us_ro_0;
   inout tst_us_ro_1;
   inout tst_us_ro_2;
   inout tst_sabil_bk;
   inout sabil_bk;

   // Internal wires
   wire DVSS;
   wire AVSS;
   wire VSS;
   wire AVDD;
   wire VDD;
   wire HDVDD;
   wire H_VDD;

   // Module instantiations
   PDDDGZ io_tst_us_sel_2_2 (
	.PAD(pad_tst_us_sel_2[2]),
	.C(tst_us_sel_2[2]));
   PDDDGZ io_tst_us_sel_2_1 (
	.PAD(pad_tst_us_sel_2[1]),
	.C(tst_us_sel_2[1]));
   PDDDGZ io_tst_us_sel_2_0 (
	.PAD(pad_tst_us_sel_2[0]),
	.C(tst_us_sel_2[0]));
   PDDDGZ io_tst_us_sel_1_3 (
	.PAD(pad_tst_us_sel_1[3]),
	.C(tst_us_sel_1[3]));
   PDDDGZ io_tst_us_sel_1_2 (
	.PAD(pad_tst_us_sel_1[2]),
	.C(tst_us_sel_1[2]));
   PDDDGZ io_tst_us_sel_1_1 (
	.PAD(pad_tst_us_sel_1[1]),
	.C(tst_us_sel_1[1]));
   PDDDGZ io_tst_us_sel_1_0 (
	.PAD(pad_tst_us_sel_1[0]),
	.C(tst_us_sel_1[0]));
   PDDDGZ io_tst_us_sel_0_3 (
	.PAD(pad_tst_us_sel_0[3]),
	.C(tst_us_sel_0[3]));
   PDDDGZ io_tst_us_sel_0_2 (
	.PAD(pad_tst_us_sel_0[2]),
	.C(tst_us_sel_0[2]));
   PDDDGZ io_tst_us_sel_0_1 (
	.PAD(pad_tst_us_sel_0[1]),
	.C(tst_us_sel_0[1]));
   PDDDGZ io_tst_us_sel_0_0 (
	.PAD(pad_tst_us_sel_0[0]),
	.C(tst_us_sel_0[0]));
   PDDDGZ io_tst_clk (
	.PAD(pad_tst_clk),
	.C(tst_clk));
   PDDDGZ io_tst_en_g (
	.PAD(pad_tst_en_g),
	.C(tst_en_g));
   PDDDGZ io_tst_wr_data_in_g (
	.PAD(pad_tst_wr_data_in_g),
	.C(tst_wr_data_in_g));
   PDDDGZ io_tst_p_en (
	.PAD(pad_tst_p_en),
	.C(tst_p_en));
   PDDDGZ io_tst_b2_ctrl_0 (
	.PAD(pad_tst_b2_ctrl[0]),
	.C(tst_b2_ctrl[0]));
   PDDDGZ io_tst_b2_ctrl_1 (
	.PAD(pad_tst_b2_ctrl[1]),
	.C(tst_b2_ctrl[1]));
   PDDDGZ io_tst_b2_ctrl_2 (
	.PAD(pad_tst_b2_ctrl[2]),
	.C(tst_b2_ctrl[2]));
   PDDDGZ io_tst_b2_ctrl_3 (
	.PAD(pad_tst_b2_ctrl[3]),
	.C(tst_b2_ctrl[3]));
   PDDDGZ io_tst_b2_ctrl_4 (
	.PAD(pad_tst_b2_ctrl[4]),
	.C(tst_b2_ctrl[4]));
   PDDDGZ io_tst_b2_ctrl_5 (
	.PAD(pad_tst_b2_ctrl[5]),
	.C(tst_b2_ctrl[5]));
   PDDDGZ io_rstn (
	.PAD(pad_rstn),
	.C(rstn));
   PDDDGZ io_clk (
	.PAD(pad_clk),
	.C(clk));
   PDDDGZ io_en_g (
	.PAD(pad_en_g),
	.C(en_g));
   PDDDGZ io_wr_data_in_g (
	.PAD(pad_wr_data_in_g),
	.C(wr_data_in_g));
   PDDDGZ io_p_en (
	.PAD(pad_p_en),
	.C(p_en));
   PDDDGZ io_tst_us_sel_2_3 (
	.PAD(pad_tst_us_sel_2[3]),
	.C(tst_us_sel_2[3]));
   PDO24CDG io_tst_couple_en (
	.I(tst_couple_en),
	.PAD(pad_tst_couple_en));
   PDO24CDG io_tst_rd_vld_g (
	.I(tst_rd_vld_g),
	.PAD(pad_tst_rd_vld_g));
   PDO24CDG io_tst_rd_data_out_g (
	.I(tst_rd_data_out_g),
	.PAD(pad_tst_rd_data_out_g));
   PDO24CDG io_tst_p_out_vld_g (
	.I(tst_p_out_vld_g),
	.PAD(pad_tst_p_out_vld_g));
   PDO24CDG io_tst_p_out_g (
	.I(tst_p_out_g),
	.PAD(pad_tst_p_out_g));
   PDO24CDG io_rd_data_out_g (
	.I(rd_data_out_g),
	.PAD(pad_rd_data_out_g));
   PDO24CDG io_rd_vld_g (
	.I(rd_vld_g),
	.PAD(pad_rd_vld_g));
   PDO24CDG io_p_out_vld_g (
	.I(p_out_vld_g),
	.PAD(pad_p_out_vld_g));
   PDO24CDG io_p_out_g (
	.I(p_out_g),
	.PAD(pad_p_out_g));
   PDO24CDG io_couple_en (
	.I(couple_en),
	.PAD(pad_couple_en));
   PDB3AC io_tst_je_ro_1 (
	.AIO(tst_je_ro_1));
   PDB3AC io_tst_je_ro_2 (
	.AIO(tst_je_ro_2));
   PDB3AC io_tst_zq_ro_1 (
	.AIO(tst_zq_ro_1));
   PDB3AC io_tst_zq_ro_2 (
	.AIO(tst_zq_ro_2));
   PDB3AC io_tst_zq_ro_3 (
	.AIO(tst_zq_ro_3));
   PDB3AC io_tst_ro_tst (
	.AIO(tst_ro_tst));
   PDB3AC io_tst_b3_f_0 (
	.AIO(tst_b3_f[0]));
   PDB3AC io_tst_b3_f_1 (
	.AIO(tst_b3_f[1]));
   PDB3AC io_tst_b3_f_2 (
	.AIO(tst_b3_f[2]));
   PDB3AC io_tst_b3_f_3 (
	.AIO(tst_b3_f[3]));
   PDB3AC io_tst_b3_f_4 (
	.AIO(tst_b3_f[4]));
   PDB3AC io_p_mod (
	.AIO(p_mod));
   PDB3AC io_p_ota_vb (
	.AIO(p_ota_vb));
   PDB3AC io_b3_cvb (
	.AIO(b3_cvb));
   PDB3AC io_cp_sel (
	.AIO(cp_sel));
   PDB3AC io_b2_cvb2 (
	.AIO(b2_cvb2));
   PDB3AC io_b2_cvb1 (
	.AIO(b2_cvb1));
   PDB3AC io_osc_vb (
	.AIO(osc_vb));
   PDB3AC io_tst_p_ota_vb (
	.AIO(tst_p_ota_vb));
   PDB3AC io_tst_cp_sel (
	.AIO(tst_cp_sel));
   PDB3AC io_tst_p_mod (
	.AIO(tst_p_mod));
   PDB3AC io_tst_b3_cvb (
	.AIO(tst_b3_cvb));
   PDB3AC io_tst_b2_cvb2 (
	.AIO(tst_b2_cvb2));
   PDB3AC io_tst_b2_cvb1 (
	.AIO(tst_b2_cvb1));
   PDB3AC io_tst_osc_vb (
	.AIO(tst_osc_vb));
   PDB3AC io_tst_us_ro_0 (
	.AIO(tst_us_ro_0));
   PDB3AC io_tst_us_ro_1 (
	.AIO(tst_us_ro_1));
   PDB3AC io_tst_us_ro_2 (
	.AIO(tst_us_ro_2));
   PDB3AC io_tst_sabil_bk (
	.AIO(tst_sabil_bk));
   PDB3AC io_sabil_bk (
	.AIO(sabil_bk));

   // Fillers and physical instances.
   PAD60NU CUP_io_tst_us_sel_2_3 (
 );
   PAD60NA CUP_io_HS_VDD2 (
 );
   PAD60NA CUP_io_HS_VSS2 (
 );
   PAD60NA CUP_io_HS_AVDD2 (
 );
   PAD60NA CUP_io_HS_AVSS2 (
 );
   PAD60NA CUP_io_tst_sabil_bk (
 );
   PAD60NA CUP_io_tst_us_ro_2 (
 );
   PAD60NA CUP_io_tst_us_ro_1 (
 );
   PAD60NA CUP_io_tst_us_ro_0 (
 );
   PAD60NA CUP_io_tst_osc_vb (
 );
   PAD60NA CUP_io_tst_b2_cvb1 (
 );
   PAD60NA CUP_io_VDD2 (
 );
   PAD60NA CUP_io_VSS2 (
 );
   PAD60NA CUP_io_tst_b2_cvb2 (
 );
   PAD60NA CUP_io_tst_b3_cvb (
 );
   PAD60NA CUP_io_tst_p_mod (
 );
   PAD60NA CUP_io_tst_cp_sel (
 );
   PAD60NA CUP_io_tst_p_ota_vb (
 );
   PAD60NA CUP_io_VDD1 (
 );
   PAD60NA CUP_io_VSS1 (
 );
   PAD60NA CUP_io_osc_vb (
 );
   PAD60NA CUP_io_b2_cvb1 (
 );
   PAD60NA CUP_io_b2_cvb2 (
 );
   PAD60NA CUP_io_cp_sel (
 );
   PAD60NA CUP_io_HS_VDD1 (
 );
   PAD60NA CUP_io_HS_VSS1 (
 );
   PAD60NA CUP_io_HS_AVDD1 (
 );
   PAD60NA CUP_io_HS_AVSS1 (
 );
   PAD60NA CUP_io_sabil_bk (
 );
   PAD60NA CUP_io_b3_cvb (
 );
   PAD60NA CUP_io_p_ota_vb (
 );
   PAD60NA CUP_io_p_mod (
 );
   PAD60NA CUP_io_VDD0 (
 );
   PAD60NA CUP_io_VSS0 (
 );
   PAD60NA CUP_io_tst_b3_f_4 (
 );
   PAD60NA CUP_io_tst_b3_f_3 (
 );
   PAD60NA CUP_io_tst_b3_f_2 (
 );
   PAD60NA CUP_io_tst_b3_f_1 (
 );
   PAD60NA CUP_io_tst_b3_f_0 (
 );
   PAD60NA CUP_io_tst_ro_tst (
 );
   PAD60NA CUP_io_tst_zq_ro_3 (
 );
   PAD60NA CUP_io_tst_zq_ro_2 (
 );
   PAD60NA CUP_io_tst_zq_ro_1 (
 );
   PAD60NA CUP_io_tst_je_ro_2 (
 );
   PAD60NA CUP_io_tst_je_ro_1 (
 );
   PAD60NA CUP_io_HS_VDD0 (
 );
   PAD60NA CUP_io_HS_VSS0 (
 );
   PAD60NA CUP_io_HS_AVDD0 (
 );
   PAD60NA CUP_io_HS_AVSS0 (
 );
   PAD60NU CUP_io_tst_b2_ctrl_5 (
 );
   PAD60NU CUP_io_tst_b2_ctrl_4 (
 );
   PAD60NU CUP_io_tst_b2_ctrl_3 (
 );
   PAD60NU CUP_io_tst_b2_ctrl_2 (
 );
   PAD60NU CUP_io_tst_b2_ctrl_1 (
 );
   PAD60NU CUP_io_tst_b2_ctrl_0 (
 );
   PAD60NU CUP_io_p_en (
 );
   PAD60NU CUP_io_couple_en (
 );
   PAD60NU CUP_io_p_out_g (
 );
   PAD60NU CUP_io_p_out_vld_g (
 );
   PAD60NU CUP_io_rd_vld_g (
 );
   PAD60NU CUP_io_rd_data_out_g (
 );
   PAD60NU CUP_io_wr_data_in_g (
 );
   PAD60NU CUP_io_en_g (
 );
   PAD60NU CUP_io_clk (
 );
   PAD60NU CUP_io_rstn (
 );
   PAD60NU CUP_io_HDVSS1 (
 );
   PAD60NU CUP_io_HDVDD1 (
 );
   PAD60NU CUP_io_HVSS1 (
 );
   PAD60NU CUP_io_HVDD1 (
 );
   PAD60NU CUP_io_tst_p_en (
 );
   PAD60NU CUP_io_tst_p_out_g (
 );
   PAD60NU CUP_io_tst_p_out_vld_g (
 );
   PAD60NU CUP_io_tst_rd_data_out_g (
 );
   PAD60NU CUP_io_tst_rd_vld_g (
 );
   PAD60NU CUP_io_tst_couple_en (
 );
   PAD60NU CUP_io_tst_wr_data_in_g (
 );
   PAD60NU CUP_io_tst_en_g (
 );
   PAD60NU CUP_io_tst_clk (
 );
   PAD60NU CUP_io_HDVSS0 (
 );
   PAD60NU CUP_io_HDVDD0 (
 );
   PAD60NU CUP_io_HVSS0 (
 );
   PAD60NU CUP_io_HVDD0 (
 );
   PAD60NU CUP_io_POC (
 );
   PAD60NU CUP_io_tst_us_sel_0_0 (
 );
   PAD60NU CUP_io_tst_us_sel_0_1 (
 );
   PAD60NU CUP_io_tst_us_sel_0_2 (
 );
   PAD60NU CUP_io_tst_us_sel_0_3 (
 );
   PAD60NU CUP_io_tst_us_sel_1_0 (
 );
   PAD60NU CUP_io_tst_us_sel_1_1 (
 );
   PAD60NU CUP_io_tst_us_sel_1_2 (
 );
   PAD60NU CUP_io_tst_us_sel_1_3 (
 );
   PAD60NU CUP_io_tst_us_sel_2_0 (
 );
   PAD60NU CUP_io_tst_us_sel_2_1 (
 );
   PAD60NU CUP_io_tst_us_sel_2_2 (
 );
   PFILLER5A filler_top_ana_S_5 (
 );
   PFILLER10A filler_top_ana_S_4 (
 );
   PFILLER20A filler_top_ana_S_3 (
 );
   PFILLER20A filler_top_ana_S_2 (
 );
   PFILLER20A filler_top_ana_S_1 (
 );
   PFILLER20A filler_top_ana_S_0 (
 );
   PFILLER5 filler_top_digi_S_3 (
 );
   PFILLER10 filler_top_digi_S_2 (
 );
   PFILLER20 filler_top_digi_S_1 (
 );
   PFILLER20 filler_top_digi_S_0 (
 );
   PFILLER5A filler_bot_ana_E_16 (
 );
   PFILLER5A filler_bot_ana_E_15 (
 );
   PFILLER10A filler_bot_ana_E_14 (
 );
   PFILLER10A filler_bot_ana_E_13 (
 );
   PFILLER20A filler_bot_ana_E_12 (
 );
   PFILLER20A filler_bot_ana_E_11 (
 );
   PFILLER20A filler_bot_ana_E_10 (
 );
   PFILLER20A filler_bot_ana_E_9 (
 );
   PFILLER20A filler_bot_ana_E_8 (
 );
   PFILLER20A filler_bot_ana_E_7 (
 );
   PFILLER20A filler_bot_ana_E_6 (
 );
   PFILLER20A filler_bot_ana_E_5 (
 );
   PFILLER20A filler_bot_ana_E_4 (
 );
   PFILLER20A filler_bot_ana_E_3 (
 );
   PFILLER20A filler_bot_ana_E_2 (
 );
   PFILLER20A filler_bot_ana_E_1 (
 );
   PFILLER20A filler_bot_ana_E_0 (
 );
   PFILLER5A filler_right_ana_N_8 (
 );
   PFILLER5A filler_right_ana_N_7 (
 );
   PFILLER20A filler_right_ana_N_6 (
 );
   PFILLER20A filler_right_ana_N_5 (
 );
   PFILLER20A filler_right_ana_N_4 (
 );
   PFILLER20A filler_right_ana_N_3 (
 );
   PFILLER20A filler_right_ana_N_2 (
 );
   PFILLER20A filler_right_ana_N_1 (
 );
   PFILLER20A filler_right_ana_N_0 (
 );
   PFILLER5A filler_top_ana_W_2 (
 );
   PFILLER20A filler_top_ana_W_1 (
 );
   PFILLER20A filler_top_ana_W_0 (
 );
   PFILLER5 filler_top_digi_W_91 (
 );
   PFILLER10 filler_top_digi_W_90 (
 );
   PFILLER10 filler_top_digi_W_89 (
 );
   PFILLER10 filler_top_digi_W_88 (
 );
   PFILLER10 filler_top_digi_W_87 (
 );
   PFILLER10 filler_top_digi_W_86 (
 );
   PFILLER10 filler_top_digi_W_85 (
 );
   PFILLER10 filler_top_digi_W_84 (
 );
   PFILLER10 filler_top_digi_W_83 (
 );
   PFILLER10 filler_top_digi_W_82 (
 );
   PFILLER10 filler_top_digi_W_81 (
 );
   PFILLER10 filler_top_digi_W_80 (
 );
   PFILLER10 filler_top_digi_W_79 (
 );
   PFILLER10 filler_top_digi_W_78 (
 );
   PFILLER10 filler_top_digi_W_77 (
 );
   PFILLER10 filler_top_digi_W_76 (
 );
   PFILLER10 filler_top_digi_W_75 (
 );
   PFILLER10 filler_top_digi_W_74 (
 );
   PFILLER10 filler_top_digi_W_73 (
 );
   PFILLER10 filler_top_digi_W_72 (
 );
   PFILLER10 filler_top_digi_W_71 (
 );
   PFILLER10 filler_top_digi_W_70 (
 );
   PFILLER10 filler_top_digi_W_69 (
 );
   PFILLER10 filler_top_digi_W_68 (
 );
   PFILLER10 filler_top_digi_W_67 (
 );
   PFILLER10 filler_top_digi_W_66 (
 );
   PFILLER10 filler_top_digi_W_65 (
 );
   PFILLER10 filler_top_digi_W_64 (
 );
   PFILLER10 filler_top_digi_W_63 (
 );
   PFILLER10 filler_top_digi_W_62 (
 );
   PFILLER10 filler_top_digi_W_61 (
 );
   PFILLER10 filler_top_digi_W_60 (
 );
   PFILLER10 filler_top_digi_W_59 (
 );
   PFILLER10 filler_top_digi_W_58 (
 );
   PFILLER10 filler_top_digi_W_57 (
 );
   PFILLER10 filler_top_digi_W_56 (
 );
   PFILLER10 filler_top_digi_W_55 (
 );
   PFILLER10 filler_top_digi_W_54 (
 );
   PFILLER10 filler_top_digi_W_53 (
 );
   PFILLER10 filler_top_digi_W_52 (
 );
   PFILLER10 filler_top_digi_W_51 (
 );
   PFILLER10 filler_top_digi_W_50 (
 );
   PFILLER10 filler_top_digi_W_49 (
 );
   PFILLER10 filler_top_digi_W_48 (
 );
   PFILLER10 filler_top_digi_W_47 (
 );
   PFILLER20 filler_top_digi_W_46 (
 );
   PFILLER20 filler_top_digi_W_45 (
 );
   PFILLER20 filler_top_digi_W_44 (
 );
   PFILLER20 filler_top_digi_W_43 (
 );
   PFILLER20 filler_top_digi_W_42 (
 );
   PFILLER20 filler_top_digi_W_41 (
 );
   PFILLER20 filler_top_digi_W_40 (
 );
   PFILLER20 filler_top_digi_W_39 (
 );
   PFILLER20 filler_top_digi_W_38 (
 );
   PFILLER20 filler_top_digi_W_37 (
 );
   PFILLER20 filler_top_digi_W_36 (
 );
   PFILLER20 filler_top_digi_W_35 (
 );
   PFILLER20 filler_top_digi_W_34 (
 );
   PFILLER20 filler_top_digi_W_33 (
 );
   PFILLER20 filler_top_digi_W_32 (
 );
   PFILLER20 filler_top_digi_W_31 (
 );
   PFILLER20 filler_top_digi_W_30 (
 );
   PFILLER20 filler_top_digi_W_29 (
 );
   PFILLER20 filler_top_digi_W_28 (
 );
   PFILLER20 filler_top_digi_W_27 (
 );
   PFILLER20 filler_top_digi_W_26 (
 );
   PFILLER20 filler_top_digi_W_25 (
 );
   PFILLER20 filler_top_digi_W_24 (
 );
   PFILLER20 filler_top_digi_W_23 (
 );
   PFILLER20 filler_top_digi_W_22 (
 );
   PFILLER20 filler_top_digi_W_21 (
 );
   PFILLER20 filler_top_digi_W_20 (
 );
   PFILLER20 filler_top_digi_W_19 (
 );
   PFILLER20 filler_top_digi_W_18 (
 );
   PFILLER20 filler_top_digi_W_17 (
 );
   PFILLER20 filler_top_digi_W_16 (
 );
   PFILLER20 filler_top_digi_W_15 (
 );
   PFILLER20 filler_top_digi_W_14 (
 );
   PFILLER20 filler_top_digi_W_13 (
 );
   PFILLER20 filler_top_digi_W_12 (
 );
   PFILLER20 filler_top_digi_W_11 (
 );
   PFILLER20 filler_top_digi_W_10 (
 );
   PFILLER20 filler_top_digi_W_9 (
 );
   PFILLER20 filler_top_digi_W_8 (
 );
   PFILLER20 filler_top_digi_W_7 (
 );
   PFILLER20 filler_top_digi_W_6 (
 );
   PFILLER20 filler_top_digi_W_5 (
 );
   PFILLER20 filler_top_digi_W_4 (
 );
   PFILLER20 filler_top_digi_W_3 (
 );
   PFILLER20 filler_top_digi_W_2 (
 );
   PFILLER20 filler_top_digi_W_1 (
 );
   PFILLER20 filler_top_digi_W_0 (
 );
   PVSS3AC io_HS_VSS2 (
 );
   PVDD3AC io_HS_VDD2 (
 );
   PRCUTA break3 (
 );
   PVSS3AC io_VSS0 (
 );
   PVDD3AC io_VDD0 (
 );
   PRCUTA break1 (
 );
   PVSS3A io_HS_AVSS1 (
 );
   PVDD3A io_HS_AVDD1 (
 );
   PVSS3AC io_HS_VSS1 (
 );
   PVDD3AC io_HS_VDD1 (
 );
   PVSS3AC io_VSS1 (
 );
   PVDD3AC io_VDD1 (
 );
   PVSS3AC io_VSS2 (
 );
   PVDD3AC io_VDD2 (
 );
   PRCUTA break2 (
 );
   PVSS3A io_HS_AVSS2 (
 );
   PVDD3A io_HS_AVDD2 (
 );
   PVDD3AC io_HS_VDD0 (
 );
   PVSS3AC io_HS_VSS0 (
 );
   PVDD3A io_HS_AVDD0 (
 );
   PVSS3A io_HS_AVSS0 (
 );
   PRCUTA break0 (
 );
   PVSS2DGZ io_HDVSS1 (
 );
   PVDD2DGZ io_HDVDD1 (
 );
   PVSS1DGZ io_HVSS1 (
 );
   PVDD1DGZ io_HVDD1 (
 );
   PVSS2DGZ io_HDVSS0 (
 );
   PVDD2DGZ io_HDVDD0 (
 );
   PVSS1DGZ io_HVSS0 (
 );
   PVDD1DGZ io_HVDD0 (
 );
   PVDD2POC io_POC (
 );
   PCORNER CORNER_BL1 (
 );
   PCORNERA CORNER_BR1 (
 );
   PCORNERA CORNER_TL1 (
 );
   PCORNERA CORNER_TR1 (
 );
endmodule

