/*
###############################################################
#  Generated by:      Cadence Innovus 19.12-s087_1
#  OS:                Linux x86_64(Host ID pdk5)
#  Generated on:      Tue Apr 28 12:35:00 2026
#  Design:            padframe
#  Command:           saveNetlist -phys -excludeLeafCell -excludeCellInst {FILL64BWP FILL32BWP FILL16BWP FILL8BWP FILL4BWP FILL3BWP FILL2BWP FILL1BWP PFILLER20 PFILLER10 PFILLER5 PFILLER1 PFILLER20A PFILLER10A PFILLER5A PFILLER1A PAD60NA PAD60NU PAD60NAU PAD60GAU PAD60NU PAD60GU PRCUTA PCORNER PCORNERA} output/padframe/padframe_enc_lvs.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : S-2021.06-SP1
// Date      : Tue Apr 28 12:33:53 2026
/////////////////////////////////////////////////////////////
module padframe (
	);
   wire [3:0] pad_tst_us_sel_2;
   wire [3:0] pad_tst_us_sel_1;
   wire [3:0] pad_tst_us_sel_0;
   wire pad_tst_clk;
   wire pad_tst_en_g;
   wire pad_tst_wr_data_in_g;
   wire pad_tst_p_en;
   wire pad_rstn;
   wire pad_clk;
   wire pad_en_g;
   wire pad_wr_data_in_g;
   wire pad_p_en;
   wire [5:0] pad_tst_b2_ctrl;
   wire tst_couple_en;
   wire tst_rd_vld_g;
   wire tst_rd_data_out_g;
   wire tst_p_out_vld_g;
   wire tst_p_out_g;
   wire rd_data_out_g;
   wire rd_vld_g;
   wire p_out_vld_g;
   wire p_out_g;
   wire couple_en;
   wire [3:0] tst_us_sel_2;
   wire [3:0] tst_us_sel_1;
   wire [3:0] tst_us_sel_0;
   wire tst_clk;
   wire tst_en_g;
   wire tst_wr_data_in_g;
   wire tst_p_en;
   wire rstn;
   wire clk;
   wire en_g;
   wire wr_data_in_g;
   wire p_en;
   wire [5:0] tst_b2_ctrl;
   wire pad_tst_couple_en;
   wire pad_tst_rd_vld_g;
   wire pad_tst_rd_data_out_g;
   wire pad_tst_p_out_vld_g;
   wire pad_tst_p_out_g;
   wire pad_rd_data_out_g;
   wire pad_rd_vld_g;
   wire pad_p_out_vld_g;
   wire pad_p_out_g;
   wire pad_couple_en;
   wire tst_je_ro_1;
   wire tst_je_ro_2;
   wire tst_zq_ro_1;
   wire tst_zq_ro_2;
   wire tst_zq_ro_3;
   wire tst_ro_tst;
   wire [4:0] tst_b3_f;
   wire p_mod;
   wire p_ota_vb;
   wire b3_cvb;
   wire cp_sel;
   wire b2_cvb2;
   wire b2_cvb1;
   wire osc_vb;
   wire tst_p_ota_vb;
   wire tst_cp_sel;
   wire tst_p_mod;
   wire tst_b3_cvb;
   wire tst_b2_cvb2;
   wire tst_b2_cvb1;
   wire tst_osc_vb;
   wire tst_us_ro_0;
   wire tst_us_ro_1;
   wire tst_us_ro_2;
   wire tst_sabil_bk;
   wire sabil_bk;

   // Internal wires
   wire DVSS;
   wire AVSS;
   wire VSS;
   wire AVDD;
   wire VDD;
   wire HDVDD;
   wire H_VDD;

   // Module instantiations
   PDDDGZ io_tst_us_sel_2_2 (
	.PAD(pad_tst_us_sel_2[2]),
	.C(tst_us_sel_2[2]));
   PDDDGZ io_tst_us_sel_2_1 (
	.PAD(pad_tst_us_sel_2[1]),
	.C(tst_us_sel_2[1]));
   PDDDGZ io_tst_us_sel_2_0 (
	.PAD(pad_tst_us_sel_2[0]),
	.C(tst_us_sel_2[0]));
   PDDDGZ io_tst_us_sel_1_3 (
	.PAD(pad_tst_us_sel_1[3]),
	.C(tst_us_sel_1[3]));
   PDDDGZ io_tst_us_sel_1_2 (
	.PAD(pad_tst_us_sel_1[2]),
	.C(tst_us_sel_1[2]));
   PDDDGZ io_tst_us_sel_1_1 (
	.PAD(pad_tst_us_sel_1[1]),
	.C(tst_us_sel_1[1]));
   PDDDGZ io_tst_us_sel_1_0 (
	.PAD(pad_tst_us_sel_1[0]),
	.C(tst_us_sel_1[0]));
   PDDDGZ io_tst_us_sel_0_3 (
	.PAD(pad_tst_us_sel_0[3]),
	.C(tst_us_sel_0[3]));
   PDDDGZ io_tst_us_sel_0_2 (
	.PAD(pad_tst_us_sel_0[2]),
	.C(tst_us_sel_0[2]));
   PDDDGZ io_tst_us_sel_0_1 (
	.PAD(pad_tst_us_sel_0[1]),
	.C(tst_us_sel_0[1]));
   PDDDGZ io_tst_us_sel_0_0 (
	.PAD(pad_tst_us_sel_0[0]),
	.C(tst_us_sel_0[0]));
   PDDDGZ io_tst_clk (
	.PAD(pad_tst_clk),
	.C(tst_clk));
   PDDDGZ io_tst_en_g (
	.PAD(pad_tst_en_g),
	.C(tst_en_g));
   PDDDGZ io_tst_wr_data_in_g (
	.PAD(pad_tst_wr_data_in_g),
	.C(tst_wr_data_in_g));
   PDDDGZ io_tst_p_en (
	.PAD(pad_tst_p_en),
	.C(tst_p_en));
   PDDDGZ io_tst_b2_ctrl_0 (
	.PAD(pad_tst_b2_ctrl[0]),
	.C(tst_b2_ctrl[0]));
   PDDDGZ io_tst_b2_ctrl_1 (
	.PAD(pad_tst_b2_ctrl[1]),
	.C(tst_b2_ctrl[1]));
   PDDDGZ io_tst_b2_ctrl_2 (
	.PAD(pad_tst_b2_ctrl[2]),
	.C(tst_b2_ctrl[2]));
   PDDDGZ io_tst_b2_ctrl_3 (
	.PAD(pad_tst_b2_ctrl[3]),
	.C(tst_b2_ctrl[3]));
   PDDDGZ io_tst_b2_ctrl_4 (
	.PAD(pad_tst_b2_ctrl[4]),
	.C(tst_b2_ctrl[4]));
   PDDDGZ io_tst_b2_ctrl_5 (
	.PAD(pad_tst_b2_ctrl[5]),
	.C(tst_b2_ctrl[5]));
   PDDDGZ io_rstn (
	.PAD(pad_rstn),
	.C(rstn));
   PDDDGZ io_clk (
	.PAD(pad_clk),
	.C(clk));
   PDDDGZ io_en_g (
	.PAD(pad_en_g),
	.C(en_g));
   PDDDGZ io_wr_data_in_g (
	.PAD(pad_wr_data_in_g),
	.C(wr_data_in_g));
   PDDDGZ io_p_en (
	.PAD(pad_p_en),
	.C(p_en));
   PDDDGZ io_tst_us_sel_2_3 (
	.PAD(pad_tst_us_sel_2[3]),
	.C(tst_us_sel_2[3]));
   PDO24CDG io_tst_couple_en (
	.I(tst_couple_en),
	.PAD(pad_tst_couple_en));
   PDO24CDG io_tst_rd_vld_g (
	.I(tst_rd_vld_g),
	.PAD(pad_tst_rd_vld_g));
   PDO24CDG io_tst_rd_data_out_g (
	.I(tst_rd_data_out_g),
	.PAD(pad_tst_rd_data_out_g));
   PDO24CDG io_tst_p_out_vld_g (
	.I(tst_p_out_vld_g),
	.PAD(pad_tst_p_out_vld_g));
   PDO24CDG io_tst_p_out_g (
	.I(tst_p_out_g),
	.PAD(pad_tst_p_out_g));
   PDO24CDG io_rd_data_out_g (
	.I(rd_data_out_g),
	.PAD(pad_rd_data_out_g));
   PDO24CDG io_rd_vld_g (
	.I(rd_vld_g),
	.PAD(pad_rd_vld_g));
   PDO24CDG io_p_out_vld_g (
	.I(p_out_vld_g),
	.PAD(pad_p_out_vld_g));
   PDO24CDG io_p_out_g (
	.I(p_out_g),
	.PAD(pad_p_out_g));
   PDO24CDG io_couple_en (
	.I(couple_en),
	.PAD(pad_couple_en));
   PDB3AC io_tst_je_ro_1 (
	.AIO(tst_je_ro_1));
   PDB3AC io_tst_je_ro_2 (
	.AIO(tst_je_ro_2));
   PDB3AC io_tst_zq_ro_1 (
	.AIO(tst_zq_ro_1));
   PDB3AC io_tst_zq_ro_2 (
	.AIO(tst_zq_ro_2));
   PDB3AC io_tst_zq_ro_3 (
	.AIO(tst_zq_ro_3));
   PDB3AC io_tst_ro_tst (
	.AIO(tst_ro_tst));
   PDB3AC io_tst_b3_f_0 (
	.AIO(tst_b3_f[0]));
   PDB3AC io_tst_b3_f_1 (
	.AIO(tst_b3_f[1]));
   PDB3AC io_tst_b3_f_2 (
	.AIO(tst_b3_f[2]));
   PDB3AC io_tst_b3_f_3 (
	.AIO(tst_b3_f[3]));
   PDB3AC io_tst_b3_f_4 (
	.AIO(tst_b3_f[4]));
   PDB3AC io_p_mod (
	.AIO(p_mod));
   PDB3AC io_p_ota_vb (
	.AIO(p_ota_vb));
   PDB3AC io_b3_cvb (
	.AIO(b3_cvb));
   PDB3AC io_cp_sel (
	.AIO(cp_sel));
   PDB3AC io_b2_cvb2 (
	.AIO(b2_cvb2));
   PDB3AC io_b2_cvb1 (
	.AIO(b2_cvb1));
   PDB3AC io_osc_vb (
	.AIO(osc_vb));
   PDB3AC io_tst_p_ota_vb (
	.AIO(tst_p_ota_vb));
   PDB3AC io_tst_cp_sel (
	.AIO(tst_cp_sel));
   PDB3AC io_tst_p_mod (
	.AIO(tst_p_mod));
   PDB3AC io_tst_b3_cvb (
	.AIO(tst_b3_cvb));
   PDB3AC io_tst_b2_cvb2 (
	.AIO(tst_b2_cvb2));
   PDB3AC io_tst_b2_cvb1 (
	.AIO(tst_b2_cvb1));
   PDB3AC io_tst_osc_vb (
	.AIO(tst_osc_vb));
   PDB3AC io_tst_us_ro_0 (
	.AIO(tst_us_ro_0));
   PDB3AC io_tst_us_ro_1 (
	.AIO(tst_us_ro_1));
   PDB3AC io_tst_us_ro_2 (
	.AIO(tst_us_ro_2));
   PDB3AC io_tst_sabil_bk (
	.AIO(tst_sabil_bk));
   PDB3AC io_sabil_bk (
	.AIO(sabil_bk));

   // Fillers and physical instances.
   PVSS3AC io_HS_VSS2 (
 );
   PVDD3AC io_HS_VDD2 (
       .TACVDD(TACVDD)
 );
   PVSS3AC io_VSS0 (
 );
   PVDD3AC io_VDD0 (
       .TACVDD(TACVDD)
 );
   PVSS3A io_HS_AVSS1 (
 );
   PVDD3A io_HS_AVDD1 (
       .TAVDD(TAVDD)
 );
   PVSS3AC io_HS_VSS1 (
 );
   PVDD3AC io_HS_VDD1 (
       .TACVDD(TACVDD)
 );
   PVSS3AC io_VSS1 (
 );
   PVDD3AC io_VDD1 (
       .TACVDD(TACVDD)
 );
   PVSS3AC io_VSS2 (
 );
   PVDD3AC io_VDD2 (
       .TACVDD(TACVDD)
 );
   PVSS3A io_HS_AVSS2 (
 );
   PVDD3A io_HS_AVDD2 (
       .TAVDD(TAVDD)
 );
   PVDD3AC io_HS_VDD0 (
       .TACVDD(TACVDD)
 );
   PVSS3AC io_HS_VSS0 (
 );
   PVDD3A io_HS_AVDD0 (
       .TAVDD(TAVDD)
 );
   PVSS3A io_HS_AVSS0 (
 );
   PVSS2DGZ io_HDVSS1 (
       .VSSPST(VSSPST) 
 );
   PVDD2DGZ io_HDVDD1 (
       .VDDPST(VDDPST) 
 );
   PVSS1DGZ io_HVSS1 (
       .VSS(VSS) 
 );
   PVDD1DGZ io_HVDD1 (
       .VDD(VDD) 
 );
   PVSS2DGZ io_HDVSS0 (
       .VSSPST(VSSPST) 
 );
   PVDD2DGZ io_HDVDD0 (
       .VDDPST(VDDPST) 
 );
   PVSS1DGZ io_HVSS0 (
       .VSS(VSS) 
 );
   PVDD1DGZ io_HVDD0 (
       .VDD(VDD) 
 );
   PVDD2POC io_POC (
       .VDDPST(VDDPST) 
 );
endmodule

