###############################################################
#  Generated by:      Cadence Innovus 19.12-s087_1
#  OS:                Linux x86_64(Host ID pdk5)
#  Generated on:      Tue Apr 28 15:49:35 2026
#  Design:            local_ctrl_row
#  Command:           create_ccopt_clock_tree_spec -filename ./ccopt/local_ctrl_row/ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   clk (period 9.500ns) in timing_config cons_mode([../syn/output/local_ctrl_row/local_ctrl_row_rm_ideal_net.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner fast_delay -early -clock_tree clk 0.150

set_ccopt_property target_max_trans_sdc -delay_corner fast_delay -late -clock_tree clk 0.400

set_ccopt_property target_max_trans_sdc -delay_corner typ_delay -early -clock_tree clk 0.150

set_ccopt_property target_max_trans_sdc -delay_corner typ_delay -late -clock_tree clk 0.400

set_ccopt_property target_max_trans_sdc -delay_corner slow_delay -early -clock_tree clk 0.150

set_ccopt_property target_max_trans_sdc -delay_corner slow_delay -late -clock_tree clk 0.400
set_ccopt_property source_output_max_trans -delay_corner fast_delay -early -clock_tree clk 0.150
set_ccopt_property source_output_max_trans -delay_corner fast_delay -early -clock_tree clk 0.150
set_ccopt_property source_output_max_trans -delay_corner typ_delay -early -clock_tree clk 0.150
set_ccopt_property source_output_max_trans -delay_corner typ_delay -early -clock_tree clk 0.150
set_ccopt_property source_output_max_trans -delay_corner slow_delay -early -clock_tree clk 0.150
set_ccopt_property source_output_max_trans -delay_corner slow_delay -early -clock_tree clk 0.150
set_ccopt_property source_output_max_trans -delay_corner fast_delay -late -clock_tree clk 0.200
set_ccopt_property source_output_max_trans -delay_corner fast_delay -late -clock_tree clk 0.200
set_ccopt_property source_output_max_trans -delay_corner typ_delay -late -clock_tree clk 0.200
set_ccopt_property source_output_max_trans -delay_corner typ_delay -late -clock_tree clk 0.200
set_ccopt_property source_output_max_trans -delay_corner slow_delay -late -clock_tree clk 0.200
set_ccopt_property source_output_max_trans -delay_corner slow_delay -late -clock_tree clk 0.200
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 9.5

# Skew group to balance non generated clock:clk in timing_config:cons_mode (sdc ../syn/output/local_ctrl_row/local_ctrl_row_rm_ideal_net.sdc)
create_ccopt_skew_group -name clk/cons_mode -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/cons_mode true
set_ccopt_property extracted_from_clock_name -skew_group clk/cons_mode clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/cons_mode cons_mode
set_ccopt_property extracted_from_delay_corners -skew_group clk/cons_mode {fast_delay fast_delay typ_delay typ_delay slow_delay slow_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

